# Generated by Django 5.1.4 on 2026-09-08 07:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0091_lot1_notes_workflow'),
        ('scolarite', '0014_alter_journalscolarite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismeAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('raison_sociale', models.CharField(blank=True, default='', max_length=255)),
                ('adresse', models.TextField(blank=True, default='')),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('contact_nom', models.CharField(blank=True, default='', max_length=150)),
                ('contact_telephone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "LMD – Organisme d'accueil",
                'verbose_name_plural': "LMD – Organismes d'accueil",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ConventionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('sujet', models.TextField()),
                ('objectifs', models.TextField(blank=True, default='')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(blank=True, default='', max_length=150)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise (à valider)'), ('VALIDEE', 'Validée (admin)'), ('REFUSEE', 'Refusée'), ('SIGNEE', 'Signée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée (rapport rendu)'), ('SOUTENUE', 'Soutenue'), ('VALIDEE_JURY', 'Validée par jury'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20)),
                ('motif_refus', models.TextField(blank=True, default='')),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_validation_admin', models.DateTimeField(blank=True, null=True)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('date_debut_effectif', models.DateField(blank=True, null=True)),
                ('date_fin_effective', models.DateField(blank=True, null=True)),
                ('date_soutenance', models.DateTimeField(blank=True, null=True)),
                ('note_rapport', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note_soutenance', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('mention', models.CharField(blank=True, default='', max_length=30)),
                ('rapport_fichier', models.FileField(blank=True, max_length=300, null=True, upload_to='stages/rapports/')),
                ('convention_pdf', models.FileField(blank=True, max_length=300, null=True, upload_to='stages/conventions/')),
                ('date_archivage', models.DateTimeField(blank=True, null=True)),
                ('commentaires', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conventions_stage', to='scolarite.anneeacademique')),
                ('archive_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_archivees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_creees', to=settings.AUTH_USER_MODEL)),
                ('encadrant_interne', models.ForeignKey(blank=True, help_text='Encadrant interne INJS (rôle ENCADRANT).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_encadrees', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conventions_stage', to='scolarite.dossieretudiant')),
                ('ref_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conventions_stage', to='formations.refformation')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_validees', to=settings.AUTH_USER_MODEL)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conventions', to='stages.organismeaccueil')),
            ],
            options={
                'verbose_name': 'LMD – Convention de stage',
                'verbose_name_plural': 'LMD – Conventions de stage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_aptitude', models.DecimalField(blank=True, decimal_places=2, help_text='Aptitude professionnelle /20', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note_integration', models.DecimalField(blank=True, decimal_places=2, help_text="Intégration dans l'équipe /20", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note_autonomie', models.DecimalField(blank=True, decimal_places=2, help_text='Autonomie et initiative /20', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note_production', models.DecimalField(blank=True, decimal_places=2, help_text='Qualité de la production /20', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('note_rapport', models.DecimalField(blank=True, decimal_places=2, help_text='Qualité du rapport de stage /20', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('appreciation_libre', models.TextField(blank=True, default='')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, help_text='Note finale /20 (moyenne pondérée des critères).', max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, choices=[('TRES_BIEN', 'Très bien'), ('BIEN', 'Bien'), ('ASSEZ_BIEN', 'Assez bien'), ('PASSABLE', 'Passable'), ('INSUFFISANT', 'Insuffisant')], default='', max_length=15)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('convention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='stages.conventionstage')),
                ('evalue_par', models.ForeignKey(blank=True, help_text="Utilisateur INJS qui a saisi l'évaluation du tuteur externe.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_stage_realisees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, help_text='Encadrant interne INJS qui valide la note finale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_stage_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Évaluation de stage',
                'verbose_name_plural': 'LMD – Évaluations de stage',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='TuteurExterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('fonction', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteurs', to='stages.organismeaccueil')),
            ],
            options={
                'verbose_name': 'LMD – Tuteur externe',
                'verbose_name_plural': 'LMD – Tuteurs externes',
                'ordering': ['organisme__nom', 'nom', 'prenom'],
                'unique_together': {('organisme', 'nom', 'prenom')},
            },
        ),
        migrations.AddField(
            model_name='conventionstage',
            name='tuteur_externe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions', to='stages.tuteurexterne'),
        ),
        migrations.AddConstraint(
            model_name='conventionstage',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ARCHIVEE'), _negated=True), fields=('etudiant', 'annee_academique'), name='uniq_convention_stage_par_etudiant_annee', violation_error_message="Un étudiant ne peut avoir qu'une seule convention de stage active par année académique."),
        ),
    ]
