# Generated by Django 6.0.3 on 2026-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_secretariat_encadrant_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DIRECTION', 'Direction'), ('DFRC', 'DFRC'), ('SECRETARIAT', 'Secrétariat'), ('SUPERVISEUR', 'Superviseur'), ('ENCADRANT', 'Encadrant'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=20),
        ),
    ]
