# Generated by Django 5.1.4 on 2026-04-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_secretariat_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTION', 'Direction'), ('DFRC', 'DFRC'), ('SECRETARIAT', 'Secrétariat'), ('SUPERVISEUR', 'Superviseur'), ('ENCADRANT', 'Encadrant'), ('PARTICIPANT', 'Participant')], default='PARTICIPANT', max_length=20),
        ),
    ]
