# Generated by Django 5.1.4 on 2026-09-06 20:58

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scolarite', '0005_affectationgroupe_evenementscolarite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferentielJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('ACTIVATION', 'Activation'), ('DESACTIVATION', 'Désactivation'), ('ARCHIVAGE', 'Archivage')], db_index=True, max_length=20)),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_referentiels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal référentiel',
                'verbose_name_plural': 'Journal référentiels',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='refjournal_cible_idx'), models.Index(fields=['action', 'horodatage'], name='refjournal_action_idx')],
            },
        ),
        migrations.CreateModel(
            name='RefGradeEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code métier unique (ex: ECRIT, VIREMENT, EXAMEN).', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Renseigner si la valeur est propre à une année académique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.anneeacademique')),
            ],
            options={
                'verbose_name': 'Référentiel – Grade enseignant',
                'verbose_name_plural': 'Référentiel – Grades enseignants',
                'ordering': ['libelle'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('libelle'), name='referentiels_refgradeenseignant_libelle_lower_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RefModePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code métier unique (ex: ECRIT, VIREMENT, EXAMEN).', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Renseigner si la valeur est propre à une année académique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.anneeacademique')),
            ],
            options={
                'verbose_name': 'Référentiel – Mode de paiement',
                'verbose_name_plural': 'Référentiel – Modes de paiement',
                'ordering': ['libelle'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('libelle'), name='referentiels_refmodepaiement_libelle_lower_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RefTypeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code métier unique (ex: ECRIT, VIREMENT, EXAMEN).', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Renseigner si la valeur est propre à une année académique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.anneeacademique')),
            ],
            options={
                'verbose_name': 'Référentiel – Type de décision',
                'verbose_name_plural': 'Référentiel – Types de décision',
                'ordering': ['libelle'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('libelle'), name='referentiels_reftypedecision_libelle_lower_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RefTypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code métier unique (ex: ECRIT, VIREMENT, EXAMEN).', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Renseigner si la valeur est propre à une année académique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.anneeacademique')),
            ],
            options={
                'verbose_name': 'Référentiel – Type de document',
                'verbose_name_plural': 'Référentiel – Types de document',
                'ordering': ['libelle'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('libelle'), name='referentiels_reftypedocument_libelle_lower_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RefTypeEspaceSportif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code métier unique (ex: ECRIT, VIREMENT, EXAMEN).', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Renseigner si la valeur est propre à une année académique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.anneeacademique')),
            ],
            options={
                'verbose_name': 'Référentiel – Type d’espace sportif',
                'verbose_name_plural': 'Référentiel – Types d’espace sportif',
                'ordering': ['libelle'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('libelle'), name='referentiels_reftypeespacesportif_libelle_lower_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RefTypeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code métier unique (ex: ECRIT, VIREMENT, EXAMEN).', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Renseigner si la valeur est propre à une année académique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.anneeacademique')),
            ],
            options={
                'verbose_name': 'Référentiel – Type d’évaluation',
                'verbose_name_plural': 'Référentiel – Types d’évaluation',
                'ordering': ['libelle'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('libelle'), name='referentiels_reftypeevaluation_libelle_lower_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RefTypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code métier unique (ex: ECRIT, VIREMENT, EXAMEN).', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Renseigner si la valeur est propre à une année académique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.anneeacademique')),
            ],
            options={
                'verbose_name': 'Référentiel – Type de frais',
                'verbose_name_plural': 'Référentiel – Types de frais',
                'ordering': ['libelle'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('libelle'), name='referentiels_reftypefrais_libelle_lower_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RefTypeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Code métier unique (ex: ECRIT, VIREMENT, EXAMEN).', max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(db_index=True, default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Renseigner si la valeur est propre à une année académique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.anneeacademique')),
            ],
            options={
                'verbose_name': 'Référentiel – Type de notification',
                'verbose_name_plural': 'Référentiel – Types de notification',
                'ordering': ['libelle'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('libelle'), name='referentiels_reftypenotification_libelle_lower_uniq')],
            },
        ),
    ]
