# Generated by Django 5.1.4 on 2026-06-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviEvaluation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Grade précis ciblé (A3, A4, B1…). Vide = toute la catégorie.', max_length=20),
        ),
    ]
