# Generated by Django 5.1.4 on 2026-06-02 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0062_alter_module_site_alter_module_site_legacy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAlerteSeuil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur', models.CharField(choices=[('taux_presence', 'Taux de présence (%)'), ('taux_absence', "Taux d'absence (%)"), ('taux_abandon', "Taux d'abandon (%)"), ('taux_execution_vh', "Taux d'exécution volume horaire (%)"), ('nb_absences_notoires', 'Absences notoires (nombre)'), ('saturation_groupe', 'Saturation du groupe (%)')], max_length=50, unique=True)),
                ('seuil_avertissement', models.FloatField(help_text='Seuil déclenchant un avertissement (ex: 70)')),
                ('seuil_critique', models.FloatField(help_text='Seuil déclenchant une alerte critique (ex: 50)')),
                ('actif', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration alerte – seuil',
                'verbose_name_plural': 'Configuration alertes – seuils',
                'ordering': ['indicateur'],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel'), ('MI_PARCOURS', 'À mi-parcours'), ('CONSOLIDE', 'Consolidé FAB + FAC'), ('FAB', 'Spécifique FAB'), ('FAC', 'Spécifique FAC')], max_length=30)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('PUBLIE', 'Publié'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('donnees_json', models.JSONField(default=dict, help_text='Snapshot des statistiques calculées')),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(blank=True, help_text='Formation ciblée (null = toutes formations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='formations.formation')),
                ('generateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationQualitative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIFF_LOG', 'Difficulté logistique'), ('DIFF_PED', 'Difficulté pédagogique'), ('DIFF_TECH', 'Difficulté technique'), ('DIFF_ORG', 'Difficulté organisationnelle'), ('POSITIF', 'Point positif')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='statistiques.rapport')),
            ],
            options={
                'verbose_name': 'Observation qualitative',
                'verbose_name_plural': 'Observations qualitatives',
                'ordering': ['rapport', 'type'],
            },
        ),
        migrations.CreateModel(
            name='SignatureRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_signataire', models.CharField(max_length=50)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('hash_rapport', models.CharField(help_text='SHA-256 du contenu du rapport au moment de la signature', max_length=64)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='statistiques.rapport')),
                ('signataire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature de rapport',
                'verbose_name_plural': 'Signatures de rapports',
                'ordering': ['-date_signature'],
            },
        ),
    ]
