# Generated by Django 5.1.4 on 2026-09-08 07:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_campagneadmission_candidature_campagne_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('formations', '0091_lot1_notes_workflow'),
        ('scolarite', '0013_alter_journalscolarite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echeancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scolarite.anneeacademique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scolarite.dossieretudiant')),
            ],
        ),
        migrations.CreateModel(
            name='LigneEcheancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('DOSSIER', 'Frais de dossier'), ('INSCRIPTION', "Frais d'inscription"), ('SCOLARITE', 'Frais de scolarité'), ('EXAMEN', "Frais d'examen"), ('DOCUMENT', 'Frais de document')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('IMPAYE', 'Impayé'), ('PAYE', 'Payé'), ('PARTIELLEMENT_PAYE', 'Partiellement payé')], default='IMPAYE', max_length=30)),
                ('echeancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finances_etudiantes.echeancier')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_emission', models.DateField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('echeancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finances_etudiantes.echeancier')),
                ('lignes', models.ManyToManyField(related_name='+', to='finances_etudiantes.ligneecheancier')),
            ],
        ),
        migrations.AddField(
            model_name='echeancier',
            name='lignes',
            field=models.ManyToManyField(related_name='+', to='finances_etudiantes.ligneecheancier'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('nature', models.CharField(choices=[('DOSSIER', 'Frais de dossier'), ('INSCRIPTION', "Frais d'inscription"), ('SCOLARITE', 'Frais de scolarité'), ('EXAMEN', "Frais d'examen"), ('DOCUMENT', 'Frais de document')], max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('CAISSE', 'Caisse'), ('VIREMENT', 'Virement'), ('ELEPHANT_MONEY', 'Orange Money'), ('MTN_MONEY', 'MTN Mobile Money'), ('MOOV_MONEY', 'Moov Money'), ('CARTE_BANCAIRE', 'Carte bancaire')], max_length=30)),
                ('statut', models.CharField(choices=[('INITIE', 'Initialisé'), ('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé'), ('REMBOSSE', 'Remboursé'), ('RAPPROCHE', 'Rapproché')], default='INITIE', max_length=20)),
                ('preuve', models.FileField(blank=True, help_text='Pièce justificative du paiement (obligatoire pour CONFIRME)', null=True, upload_to='finances_proofs/')),
                ('transaction_externe', models.CharField(blank=True, help_text='Identifiant unique de transaction externe (anti-doublon)', max_length=200, null=True, unique=True)),
                ('date_rapprochement', models.DateTimeField(blank=True, null=True)),
                ('audit_trail', models.JSONField(blank=True, default=dict)),
                ('candidat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='admissions.candidat')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.dossieretudiant')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('date_echeance', models.DateField()),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finances_etudiantes.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='RapprochementComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_periode', models.DateField()),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commentaire', models.TextField(blank=True)),
                ('transactions', models.ManyToManyField(related_name='+', to='finances_etudiantes.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Relance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_relance', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('LETTRE', 'Lettre')], max_length=20)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('echeancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finances_etudiantes.echeancier')),
            ],
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('INITIE', 'Initialisé'), ('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué'), ('ANNULE', 'Annulé'), ('REMBOSSE', 'Remboursé'), ('RAPPROCHE', 'Rapproché')], default='INITIE', max_length=20)),
                ('transaction_externe', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paiement_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finances_etudiantes.paiement')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('DOSSIER', 'Frais de dossier'), ('INSCRIPTION', "Frais d'inscription"), ('SCOLARITE', 'Frais de scolarité'), ('EXAMEN', "Frais d'examen"), ('DOCUMENT', 'Frais de document')], max_length=50)),
                ('montant_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(default='XOF', max_length=3)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scolarite.anneeacademique')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='formations.refformation')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='scolarite.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scolarite.parcours')),
            ],
            options={
                'ordering': ['-date_creation'],
                'unique_together': {('formation', 'parcours', 'niveau', 'annee_academique', 'nature')},
            },
        ),
    ]
