# Generated by Django 5.1.4 on 2026-09-07 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('formations', '0088_alter_participant_options'),
        ('scolarite', '0007_alter_journalscolarite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_fermeture', models.DateField(blank=True, null=True)),
                ('quota_admissibles', models.PositiveSmallIntegerField(blank=True, help_text='Nombre de candidats déclarés admissibles.', null=True)),
                ('quota_admis', models.PositiveSmallIntegerField(blank=True, help_text="Nombre d'admis au terme de la sélection.", null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIEE', 'Planifiée'), ('OUVERTE', 'Ouverte'), ('SUSPENDUE', 'Suspendue'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='scolarite.anneeacademique')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='scolarite.parcours')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes', to='formations.refformation')),
            ],
            options={
                'verbose_name': 'Admission – Campagne',
                'verbose_name_plural': 'Admission – Campagnes',
                'ordering': ['-annee_academique__libelle', 'ref_formation__intitule'],
            },
        ),
        migrations.AddField(
            model_name='candidature',
            name='campagne',
            field=models.ForeignKey(blank=True, help_text="Campagne d'admission de rattachement. Une campagne clôturée n'accepte plus de candidature.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='admissions.campagneadmission'),
        ),
        migrations.CreateModel(
            name='ClassementConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.PositiveSmallIntegerField()),
                ('score_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('liste', models.CharField(choices=[('ADMISSIBLE', 'Admissible'), ('LISTE_ATTENTE', "Liste d'attente"), ('NON_ADMIS', 'Non admis')], max_length=20)),
                ('publie', models.BooleanField(default=False)),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='admissions.campagneadmission')),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classements', to='admissions.candidature')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classements_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission – Classement',
                'verbose_name_plural': 'Admission – Classements',
                'ordering': ['campagne', 'rang'],
            },
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ECRIT', 'Écrit'), ('ORAL', 'Oral'), ('PRATIQUE', 'Pratique'), ('PHYSIQUE', 'Physique')], max_length=10)),
                ('intitule', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree_minutes', models.PositiveSmallIntegerField(default=60)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('verrouillee', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='admissions.campagneadmission')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves', to='formations.refsite', verbose_name='Centre (site)')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epreuves', to='formations.refsalle')),
            ],
            options={
                'verbose_name': 'Admission – Épreuve',
                'verbose_name_plural': 'Admission – Épreuves',
                'ordering': ['date', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='ConvocationEpreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('convoque_le', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='admissions.candidature')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='admissions.epreuve')),
            ],
            options={
                'verbose_name': 'Admission – Convocation',
                'verbose_name_plural': 'Admission – Convocations',
            },
        ),
        migrations.CreateModel(
            name='NoteConcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, help_text='Note obtenue (null = non noté).', max_digits=5, null=True)),
                ('absent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_concours', to='admissions.candidature')),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='admissions.epreuve')),
            ],
            options={
                'verbose_name': 'Admission – Note de concours',
                'verbose_name_plural': 'Admission – Notes de concours',
            },
        ),
        migrations.CreateModel(
            name='NoteConcoursHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nouvelle_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_notes_concours', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='admissions.noteconcours')),
            ],
            options={
                'verbose_name': 'Admission – Historique de note',
                'verbose_name_plural': 'Admission – Historiques de note',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='SurveillanceEpreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveillances', to='admissions.epreuve')),
                ('surveillant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveillances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission – Surveillance d’épreuve',
                'verbose_name_plural': 'Admission – Surveillances d’épreuve',
            },
        ),
        migrations.AddConstraint(
            model_name='campagneadmission',
            constraint=models.UniqueConstraint(fields=('annee_academique', 'ref_formation', 'parcours'), name='uniq_campagne_par_annee_formation_parcours'),
        ),
        migrations.AddConstraint(
            model_name='classementconcours',
            constraint=models.UniqueConstraint(fields=('campagne', 'candidature'), name='uniq_classement_par_campagne'),
        ),
        migrations.AddConstraint(
            model_name='classementconcours',
            constraint=models.UniqueConstraint(fields=('campagne', 'rang'), name='uniq_rang_par_campagne'),
        ),
        migrations.AddConstraint(
            model_name='convocationepreuve',
            constraint=models.UniqueConstraint(fields=('epreuve', 'candidature'), name='uniq_convocation_par_epreuve'),
        ),
        migrations.AddConstraint(
            model_name='noteconcours',
            constraint=models.UniqueConstraint(fields=('epreuve', 'candidature'), name='uniq_note_par_epreuve'),
        ),
        migrations.AddConstraint(
            model_name='surveillanceepreuve',
            constraint=models.UniqueConstraint(fields=('epreuve', 'surveillant'), name='uniq_surveillance_par_epreuve'),
        ),
    ]
