# Generated by Django 5.1.4 on 2026-08-27 19:22

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0087_widen_grade_categorie_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('cycle', models.CharField(choices=[('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat')], default='LICENCE', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=1, help_text='Ordre de progression (L1=1, L2=2…)')),
                ('credits_requis', models.PositiveSmallIntegerField(default=60, help_text='Crédits ECTS requis pour valider le niveau.')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LMD – Niveau',
                'verbose_name_plural': 'LMD – Niveaux',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RegimeEtudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "LMD – Régime d'études",
                'verbose_name_plural': "LMD – Régimes d'études",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='StatutEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('bloque_inscription', models.BooleanField(default=False, help_text='Empêche toute nouvelle inscription tant que ce statut est actif.')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LMD – Statut étudiant',
                'verbose_name_plural': 'LMD – Statuts étudiant',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LMD – Type de formation',
                'verbose_name_plural': 'LMD – Types de formation',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Format attendu : 2026-2027', max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('courante', models.BooleanField(default=False, help_text='Une seule année peut être courante à la fois.')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LMD – Année académique',
                'verbose_name_plural': 'LMD – Années académiques',
                'ordering': ['-libelle'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('courante', True)), fields=('courante',), name='uniq_annee_academique_courante')],
            },
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('intitule', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcours_lmd', to='formations.refformation', verbose_name='Formation (cycle)')),
                ('type_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcours', to='scolarite.typeformation')),
            ],
            options={
                'verbose_name': 'LMD – Parcours',
                'verbose_name_plural': 'LMD – Parcours',
                'ordering': ['ref_formation__intitule', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Maquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquettes', to='scolarite.anneeacademique')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquettes', to='formations.refformation', verbose_name='Formation (cycle)')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquettes', to='scolarite.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maquettes', to='scolarite.parcours')),
            ],
            options={
                'verbose_name': 'LMD – Maquette pédagogique',
                'verbose_name_plural': 'LMD – Maquettes pédagogiques',
                'ordering': ['-annee_academique__libelle', 'niveau__ordre', '-version'],
                'unique_together': {('annee_academique', 'ref_formation', 'parcours', 'niveau', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(help_text='Numéro global du semestre (S1 → 1, S6 → 6)')),
                ('libelle', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='scolarite.niveau')),
            ],
            options={
                'verbose_name': 'LMD – Semestre',
                'verbose_name_plural': 'LMD – Semestres',
                'ordering': ['numero'],
                'unique_together': {('niveau', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('intitule', models.CharField(max_length=255)),
                ('credits', models.PositiveSmallIntegerField(default=0, verbose_name='Crédits ECTS')),
                ('caractere', models.CharField(choices=[('OBLIGATOIRE', 'Obligatoire'), ('OPTIONNELLE', 'Optionnelle'), ('LIBRE', 'Libre')], default='OBLIGATOIRE', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('maquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites_enseignement', to='scolarite.maquette')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites_enseignement', to='scolarite.semestre')),
            ],
            options={
                'verbose_name': "LMD – Unité d'enseignement",
                'verbose_name_plural': "LMD – Unités d'enseignement",
                'ordering': ['semestre__numero', 'ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ECUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('intitule', models.CharField(max_length=255)),
                ('credits', models.PositiveSmallIntegerField(default=0, verbose_name='Crédits ECTS')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('volume_cm', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Volume CM (h)')),
                ('volume_td', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Volume TD (h)')),
                ('volume_tp', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Volume TP (h)')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('ref_module', models.ForeignKey(blank=True, help_text='Module opérationnel correspondant. Ce lien permet de générer les inscriptions aux modules à partir des inscriptions pédagogiques.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecues', to='formations.refmodule')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecues', to='scolarite.ue')),
            ],
            options={
                'verbose_name': 'LMD – ECUE',
                'verbose_name_plural': 'LMD – ECUE',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: L1-G1', max_length=50)),
                ('capacite_max', models.PositiveSmallIntegerField(blank=True, help_text='Effectif maximum. Vide = pas de limite.', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes', to='scolarite.anneeacademique')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes_lmd', to='formations.refformation', verbose_name='Formation (cycle)')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_lmd', to='formations.refsite')),
                ('vague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_lmd', to='formations.refvague')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupes', to='scolarite.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groupes', to='scolarite.parcours')),
            ],
            options={
                'verbose_name': 'LMD – Groupe',
                'verbose_name_plural': 'LMD – Groupes',
                'ordering': ['annee_academique__libelle', 'niveau__ordre', 'nom'],
                'indexes': [models.Index(fields=['annee_academique', 'niveau'], name='scolarite_g_annee_a_dfd5f7_idx')],
                'constraints': [models.UniqueConstraint(models.F('annee_academique'), models.F('ref_formation'), models.F('niveau'), django.db.models.functions.text.Lower('nom'), name='uniq_groupe_annee_formation_niveau_nom_ci')],
            },
        ),
        migrations.AddConstraint(
            model_name='parcours',
            constraint=models.UniqueConstraint(models.F('ref_formation'), django.db.models.functions.text.Lower('code'), name='uniq_parcours_formation_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='ue',
            constraint=models.UniqueConstraint(models.F('maquette'), django.db.models.functions.text.Lower('code'), name='uniq_ue_maquette_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='ecue',
            constraint=models.UniqueConstraint(models.F('ue'), django.db.models.functions.text.Lower('code'), name='uniq_ecue_ue_code_ci'),
        ),
    ]
