# Generated by Django 5.1.4 on 2026-08-27 20:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('formations', '0087_widen_grade_categorie_fields'),
        ('scolarite', '0002_journalscolarite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_premiere_inscription', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dossier_etudiant', to='formations.participant')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='scolarite.statutetudiant')),
            ],
            options={
                'verbose_name': 'LMD – Dossier étudiant',
                'verbose_name_plural': 'LMD – Dossiers étudiants',
                'ordering': ['participant__nom', 'participant__prenom'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_inscription', models.CharField(choices=[('PREMIERE', 'Première inscription'), ('REINSCRIPTION', 'Réinscription'), ('REDOUBLEMENT', 'Redoublement'), ('REPRISE', 'Reprise après suspension'), ('REORIENTATION', 'Réorientation'), ('TRANSFERT', 'Transfert')], default='PREMIERE', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('A_VALIDER', 'À valider'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminée')], default='BROUILLON', max_length=20)),
                ('date_inscription', models.DateField(default=django.utils.timezone.localdate)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions', to='admissions.admission', verbose_name="Admission d'origine")),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='scolarite.anneeacademique')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_lmd', to='formations.refcategorie')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='scolarite.dossieretudiant')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_lmd', to='formations.refgrade')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='scolarite.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='scolarite.parcours')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_lmd', to='formations.refformation', verbose_name='Formation (cycle)')),
                ('regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='scolarite.regimeetudes')),
                ('statut_etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='scolarite.statutetudiant')),
                ('vague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_lmd', to='formations.refvague')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Inscription administrative',
                'verbose_name_plural': 'LMD – Inscriptions administratives',
                'ordering': ['-annee_academique__libelle', 'etudiant__participant__nom'],
                'indexes': [models.Index(fields=['annee_academique', 'statut'], name='scolarite_i_annee_a_1f93e4_idx'), models.Index(fields=['ref_formation', 'niveau'], name='scolarite_i_ref_for_8b8bf1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'VALIDEE')), fields=('etudiant', 'annee_academique', 'ref_formation', 'parcours', 'niveau'), name='uniq_inscription_validee_par_annee_formation_niveau')],
            },
        ),
    ]
