# Generated by Django 5.1.4 on 2026-08-27 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0004_inscriptionpedagogique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('motif', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_groupes', to=settings.AUTH_USER_MODEL)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='scolarite.groupe')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='scolarite.inscriptionadministrative')),
            ],
            options={
                'verbose_name': 'LMD – Affectation de groupe',
                'verbose_name_plural': 'LMD – Affectations de groupe',
                'ordering': ['-date_debut', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('inscription',), name='uniq_affectation_active_par_inscription')],
            },
        ),
        migrations.CreateModel(
            name='EvenementScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('PASSAGE', 'Passage en année supérieure'), ('REDOUBLEMENT', 'Redoublement'), ('REPRISE', 'Reprise après suspension'), ('REORIENTATION', 'Changement de parcours'), ('CHANGEMENT_FORMATION', 'Changement de formation'), ('CHANGEMENT_GROUPE', 'Changement de groupe'), ('SUSPENSION', 'Suspension'), ('ABANDON', 'Abandon'), ('TRANSFERT', 'Transfert'), ('DIPLOMATION', 'Obtention du diplôme')], max_length=30)),
                ('date_evenement', models.DateField(default=django.utils.timezone.localdate)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=255)),
                ('nouvelle_valeur', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_scolarite', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='scolarite.dossieretudiant')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='scolarite.inscriptionadministrative')),
            ],
            options={
                'verbose_name': 'LMD – Événement de scolarité',
                'verbose_name_plural': 'LMD – Événements de scolarité',
                'ordering': ['-date_evenement', '-id'],
                'indexes': [models.Index(fields=['etudiant', 'date_evenement'], name='scolarite_e_etudian_73dba2_idx')],
            },
        ),
    ]
