# Generated by Django 5.1.4 on 2026-09-06 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0005_affectationgroupe_evenementscolarite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ecue',
            name='archive',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='maquette',
            name='activee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquette',
            name='activee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquettes_activees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maquette',
            name='commentaire_validation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maquette',
            name='validee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquette',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquettes_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maquette',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', max_length=20),
        ),
        migrations.CreateModel(
            name='MaquetteJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('VALIDATION', 'Validation'), ('ACTIVATION', 'Activation'), ('ARCHIVAGE', 'Archivage'), ('CLONAGE', 'Clonage')], db_index=True, max_length=20)),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('maquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='scolarite.maquette')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_maquettes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Journal de maquette',
                'verbose_name_plural': 'LMD – Journaux de maquette',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['maquette', 'horodatage'], name='maqjournal_maq_date_idx')],
            },
        ),
    ]
