# Generated by Django 5.1.4 on 2026-09-07 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0091_lot1_notes_workflow'),
        ('scolarite', '0010_indisponibiliteenseignant_affectationpedagogique'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleValidationLMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_admission', models.DecimalField(decimal_places=2, default=10, help_text='Moyenne /20 requise pour valider une UE ou un semestre.', max_digits=4)),
                ('compensation', models.CharField(choices=[('AUCUNE', 'Aucune compensation'), ('SEMESTRE', 'Compensation au sein du semestre')], default='SEMESTRE', max_length=12)),
                ('seuil_elim', models.DecimalField(blank=True, decimal_places=2, help_text='Moyenne UE en dessous de ce seuil : UE non acquise, même avec compensation.', max_digits=4, null=True)),
                ('credits_semestre', models.PositiveSmallIntegerField(default=30, help_text='Crédits ECTS attendus par semestre.')),
                ('capitalisation_activee', models.BooleanField(default=True, help_text='Report des crédits acquis des sessions antérieures.')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau', models.ForeignKey(blank=True, help_text='Niveau ciblé (null = règle par défaut de la formation).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles_validation_lmd', to='scolarite.niveau')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_validation_lmd', to='formations.refformation')),
            ],
            options={
                'verbose_name': 'LMD – Règle de validation',
                'verbose_name_plural': 'LMD – Règles de validation',
                'ordering': ['ref_formation', 'niveau__ordre'],
                'constraints': [models.UniqueConstraint(fields=('ref_formation', 'niveau'), name='uniq_regle_formation_niveau'), models.UniqueConstraint(condition=models.Q(('niveau__isnull', True)), fields=('ref_formation',), name='uniq_regle_defaut_formation')],
            },
        ),
    ]
