# Generated by Django 5.1.4 on 2026-09-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0012_alter_journalscolarite_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalscolarite',
            name='action',
            field=models.CharField(choices=[('CANDIDATURE_CREEE', 'Candidature créée'), ('CANDIDATURE_TRANSITION', 'Changement de statut de candidature'), ('PIECE_DEPOSEE', 'Pièce déposée'), ('PIECE_VERIFIEE', 'Pièce vérifiée'), ('ADMISSION_CREEE', 'Admission créée'), ('ADMISSION_DECISION', 'Décision d’admission'), ('ADMISSION_ANNULEE', 'Admission annulée'), ('CAMPAGNE_CREEE', 'Campagne d’admission créée'), ('CAMPAGNE_TRANSITION', 'Changement de statut de campagne'), ('CONCOURS_CONVOCATIONS', 'Convocations générées'), ('CONCOURS_EPREUVE_VERROUILLEE', 'Épreuve verrouillée'), ('CONCOURS_NOTE_CORRIGEE', 'Note de concours corrigée'), ('CONCOURS_CLASSEMENT_CALCULE', 'Classement calculé'), ('CONCOURS_CLASSEMENT_PUBLIE', 'Classement publié'), ('INSCRIPTION_CREEE', 'Inscription administrative créée'), ('INSCRIPTION_TRANSITION', 'Changement de statut d’inscription'), ('MATRICULE_GENERE', 'Matricule généré'), ('INSCRIPTION_PEDAGOGIQUE_GENEREE', 'Inscriptions pédagogiques générées'), ('INSCRIPTION_PEDAGOGIQUE_MANUELLE', 'Modification pédagogique manuelle'), ('GROUPE_AFFECTATION', 'Affectation à un groupe'), ('GROUPE_CHANGEMENT', 'Changement de groupe'), ('REINSCRIPTION', 'Réinscription'), ('EVENEMENT_SCOLARITE', 'Événement de scolarité'), ('SYNCHRONISATION_EDT', 'Export vers l’emploi du temps'), ('JURY_SESSION_CREEE', 'Session de jury créée'), ('JURY_TRANSITION', 'Changement d’état d’une session de jury'), ('JURY_MEMBRE', 'Membre de jury ajouté'), ('JURY_CALCUL', 'Propositions calculées par le moteur ECTS'), ('JURY_DECISION', 'Décision de jury enregistrée'), ('JURY_PV_GENERE', 'PV de jury généré'), ('JURY_PUBLICATION', 'Décisions de jury publiées'), ('DIPLOME_VALIDATION_PENDING', 'Diplôme en attente de validation'), ('DIPLOME_VALIDE', 'Diplôme validé'), ('DIPLOME_REVOQUE', 'Diplôme révoqué'), ('DIPLOME_REEDITE', 'Diplôme réédité')], max_length=50),
        ),
    ]
