services:
  - type: web
    name: qr-badge
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: SQLITE_DIR
        value: "/opt/render/project/src/data"
