# Generated by Django 6.0.3 on 2026-03-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0002_alter_pointage_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together=set(),
        ),
    ]
