# Generated by Django 6.0.3 on 2026-03-26 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0004_pointage_formateur_alter_pointage_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_info', models.CharField(blank=True, default='', max_length=500)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_bindings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liaison appareil',
                'verbose_name_plural': 'Liaisons appareils',
            },
        ),
    ]
