# Generated by Django 6.0.3 on 2026-03-29 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0013_secretariat_and_participant_secretariat'),
        ('presences', '0005_devicebinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Séance liée à ce pointage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='formations.sessionformation'),
        ),
    ]
