# Generated by Django 5.1.4 on 2026-04-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0045_remove_formation_fk_from_sessionformation'),
        ('presences', '0009_alter_auditlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='formation',
        ),
        migrations.AlterField(
            model_name='pointage',
            name='session',
            field=models.ForeignKey(default=8, help_text='Séance liée à ce pointage', on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='formations.sessionformation'),
            preserve_default=False,
        ),
    ]
