# Generated by Django 5.1.4 on 2026-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presences', '0013_pointage_encadrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='cible_type',
            field=models.CharField(blank=True, default='', help_text="'participant', 'formateur' ou 'encadrant'", max_length=20),
        ),
    ]
