# Generated by Django 5.1.4 on 2026-09-07 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0090_refsalle_type_espace'),
        ('presences', '0024_auditlog_module_unarchive_action'),
        ('scolarite', '0010_indisponibiliteenseignant_affectationpedagogique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='annee_academique',
            field=models.ForeignKey(blank=True, help_text="Année académique LMD (déduite de l'inscription de l'étudiant).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_lmd', to='scolarite.anneeacademique'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='ecue_lmd',
            field=models.ForeignKey(blank=True, help_text='ECUE via la passerelle Module.ref_module (chaîne LMD).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_lmd', to='scolarite.ecue'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='groupe_lmd',
            field=models.ForeignKey(blank=True, help_text="Groupe LMD (scolarite.Groupe) de l'étudiant pour cette séance.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages_lmd', to='scolarite.groupe'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='statut_assiduite',
            field=models.CharField(blank=True, choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('ABSENCE_JUSTIFIEE', 'Absence justifiée'), ('EXCUSE', 'Excusé'), ('NON_RENSEIGNE', 'Non renseigné')], help_text="Statut d'assiduité pédagogique. Null = non renseigné. Mapping depuis le statut de processus : voir MAPPING_ASSIDUITE.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SCAN_ENTREE', 'Scan entrée (QR public)'), ('SCAN_SORTIE', 'Scan sortie (QR public)'), ('SCAN_SECURE_ENTREE', 'Scan sécurisé entrée (mobile)'), ('SCAN_SECURE_SORTIE', 'Scan sécurisé sortie (mobile)'), ('FORCE_ENTREE', 'Entrée forcée (encadrant/DFRC)'), ('FORCE_SORTIE', 'Sortie forcée (encadrant/DFRC)'), ('CLOSE_SESSION', 'Fermeture de session (encadrant/DFRC)'), ('AUTO_ABSENT', 'Absent automatique (délai badge sortie dépassé)'), ('SCAN_HEARTBEAT', 'Heartbeat mobile géolocalisé'), ('NO_HEARTBEAT', 'Alerte absence heartbeat mobile'), ('OUT_OF_GEOFENCE', 'Sortie du périmètre géographique'), ('AUTO_EXIT', 'Sortie automatique (heartbeat/geofence)'), ('DEVICE_UNBIND', 'Déliaison appareil'), ('FORMATION_CREATE', 'Création de formation'), ('FORMATION_UPDATE', 'Modification de formation'), ('FORMATION_DELETE', 'Suppression de formation'), ('FORMATION_STATUT', 'Changement de statut de formation'), ('FORMATION_ASSIGN_SUPERVISEUR', 'Assignation superviseur'), ('MODULE_ASSIGN_SUPERVISEUR', 'Assignation encadrant à un module'), ('MODULE_CREATE', 'Création de module'), ('MODULE_UPDATE', 'Modification de module'), ('MODULE_DELETE', 'Suppression de module'), ('MODULE_ARCHIVE', 'Archivage de module'), ('MODULE_UNARCHIVE', 'Désarchivage de module'), ('FORMATION_QR_GENERATE', 'Génération QR code'), ('SEANCE_CREATE', 'Création de séance'), ('SEANCE_START', 'Démarrage de séance'), ('SEANCE_STOP', 'Arrêt de séance'), ('SEANCE_UPDATE', 'Modification de séance'), ('SEANCE_DELETE', 'Suppression de séance'), ('SEANCE_IMPORT', 'Import séances (Excel)'), ('PARTICIPANT_CREATE', "Création d'auditeur"), ('PARTICIPANT_UPDATE', "Modification d'auditeur"), ('PARTICIPANT_DELETE', "Suppression d'auditeur"), ('PARTICIPANT_ADD_FORMATION', 'Inscription auditeur à formation'), ('PARTICIPANT_REMOVE_FORMATION', 'Désinscription auditeur de formation'), ('PARTICIPANT_IMPORT', 'Import auditeurs (Excel)'), ('RATTRAPAGE_CREATE', "Création d'un rattrapage inter-cohorte"), ('RATTRAPAGE_PRESENCE', 'Présence générée pour un rattrapage'), ('RATTRAPAGE_CANCEL', "Annulation d'un rattrapage"), ('FORMATEUR_CREATE', 'Création de formateur'), ('FORMATEUR_UPDATE', 'Modification de formateur'), ('FORMATEUR_DELETE', 'Suppression de formateur'), ('FORMATEUR_ADD_FORMATION', 'Assignation formateur à formation'), ('FORMATEUR_REMOVE_FORMATION', 'Retrait formateur de formation'), ('FORMATEUR_IMPORT', 'Import formateurs (Excel)'), ('USER_CREATE', "Création d'utilisateur"), ('USER_UPDATE', "Modification d'utilisateur"), ('USER_DELETE', "Suppression d'utilisateur"), ('USER_LOGIN', 'Connexion utilisateur'), ('USER_LOGOUT', 'Déconnexion utilisateur'), ('USER_PASSWORD_CHANGE', 'Changement de mot de passe'), ('SECRETARIAT_CREATE', 'Création de secrétariat'), ('SECRETARIAT_UPDATE', 'Modification de secrétariat'), ('SECRETARIAT_DELETE', 'Suppression de secrétariat'), ('REFERENTIEL_CREATE', 'Création référentiel'), ('REFERENTIEL_UPDATE', 'Modification référentiel'), ('REFERENTIEL_DELETE', 'Suppression référentiel'), ('IMPORT_EXCEL', 'Import Excel global'), ('FINANCE_AJUSTEMENT_PROPOSE', 'Proposition ajustement horaire finance'), ('FINANCE_AJUSTEMENT_VALIDE', 'Validation ajustement horaire finance'), ('FINANCE_AJUSTEMENT_REJETE', 'Rejet ajustement horaire finance'), ('FINANCE_SETTINGS_UPDATE', 'Modification paramètres finance'), ('POINTAGE_MODIFIE', 'Modification de présence après clôture')], max_length=40),
        ),
        migrations.CreateModel(
            name='NotificationAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('niveau', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement'), ('CRITIQUE', 'Critique')], default='AVERTISSEMENT', max_length=15)),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_absence_emises', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ForeignKey(help_text='Destinataire (Direction / Secrétariat).', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_absence', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_absence', to='scolarite.dossieretudiant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_absence', to='formations.sessionmodule')),
            ],
            options={
                'verbose_name': 'Notification d’absence',
                'verbose_name_plural': 'Notifications d’absence',
                'ordering': ['-cree_le'],
            },
        ),
    ]
