# Generated by Django 5.1.4 on 2026-09-08 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0091_lot1_notes_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=30, unique=True)),
                ('marque', models.CharField(blank=True, default='', max_length=100)),
                ('modele', models.CharField(blank=True, default='', max_length=100)),
                ('annee_mise_en_circulation', models.PositiveIntegerField(blank=True, null=True)),
                ('kilometrage', models.PositiveIntegerField(default=0)),
                ('prochaine_revision', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LMD – Véhicule',
                'ordering': ['immatriculation'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_equipement', models.CharField(choices=[('INFO', 'Informatique'), ('SPORT', 'Matériel sportif'), ('MOBILIER', 'Mobilier'), ('ELECTRO', 'Électroménager'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15)),
                ('marque', models.CharField(blank=True, default='', max_length=100)),
                ('modele', models.CharField(blank=True, default='', max_length=100)),
                ('num_serie', models.CharField(blank=True, default='', max_length=100)),
                ('etat', models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('HORS_SERVICE', 'Hors service'), ('EN_MAINTENANCE', 'En maintenance'), ('REVOYE', 'Réformé')], default='FONCTIONNEL', max_length=15)),
                ('date_acquisition', models.DateField(blank=True, null=True)),
                ('note_inventaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_crees', to=settings.AUTH_USER_MODEL)),
                ('espace', models.ForeignKey(blank=True, help_text="Salle d'affectation (source : référentiel formations).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements_patrimoine', to='formations.refsalle')),
            ],
            options={
                'verbose_name': 'LMD – Équipement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateField()),
                ('commentaires', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaires_realises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Inventaire',
                'ordering': ['-date_inventaire'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CORRECTIVE', 'Corrective')], default='CORRECTIVE', max_length=15)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='patrimoine.equipement')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_suivies', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='formations.refsalle')),
            ],
            options={
                'verbose_name': 'LMD – Maintenance',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('statut', models.CharField(choices=[('PROVISOIRE', 'Provisoire'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='PROVISOIRE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_demandees', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='formations.refsalle')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Réservation d’espace',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='MouvementPatrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ACQUISITION', 'Acquisition'), ('AFFECTATION', 'Affectation'), ('MUTATION', 'Mutation'), ('MAINTENANCE', 'Maintenance'), ('REFORME', 'Réforme'), ('MISE_EN_SERVICE', 'Mise en service')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('ancienne_valeur', models.JSONField(blank=True, default=dict)),
                ('nouvelle_valeur', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='patrimoine.equipement')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='patrimoine.vehicule')),
            ],
            options={
                'verbose_name': 'LMD – Mouvement patrimonial',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_constate', models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('HORS_SERVICE', 'Hors service'), ('EN_MAINTENANCE', 'En maintenance'), ('REVOYE', 'Réformé')], default='FONCTIONNEL', max_length=15)),
                ('commentaires', models.TextField(blank=True, default='')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_inventaire', to='patrimoine.equipement')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='patrimoine.inventaire')),
            ],
            options={
                'verbose_name': 'LMD – Ligne d’inventaire',
                'unique_together': {('inventaire', 'equipement')},
            },
        ),
    ]
