# Generated by Django 5.1.4 on 2026-08-27 19:57

import admissions.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0087_widen_grade_categorie_fields'),
        ('scolarite', '0002_journalscolarite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission – Type de candidature',
                'verbose_name_plural': 'Admission – Types de candidature',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='TypePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('obligatoire_par_defaut', models.BooleanField(default=True)),
                ('avec_date_expiration', models.BooleanField(default=False, help_text='La pièce a une date de validité (ex: certificat médical).')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admission – Type de pièce',
                'verbose_name_plural': 'Admission – Types de pièce',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='VoieAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Admission – Voie d'accès",
                'verbose_name_plural': "Admission – Voies d'accès",
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('telephone2', models.CharField(blank=True, max_length=30)),
                ('adresse', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(blank=True, help_text='Renseigné lors de la conversion en étudiant inscrit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidat', to='formations.participant')),
            ],
            options={
                'verbose_name': 'Admission – Candidat',
                'verbose_name_plural': 'Admission – Candidats',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_candidature', models.DateField(default=django.utils.timezone.localdate)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_ATTENTE_DE_VERIFICATION', 'En attente de vérification'), ('PIECES_INCOMPLETES', 'Pièces incomplètes'), ('PIECES_VALIDEES', 'Pièces validées'), ('EN_ETUDE', 'En étude'), ('ADMISSIBLE', 'Admissible'), ('ADMIS', 'Admis'), ('ADMIS_SOUS_RESERVE', 'Admis sous réserve'), ('LISTE_ATTENTE', "Liste d'attente"), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=30)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('observations', models.TextField(blank=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='scolarite.anneeacademique')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='admissions.candidat')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_decidees', to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='scolarite.niveau', verbose_name='Niveau demandé')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='scolarite.parcours')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='formations.refformation', verbose_name='Formation (cycle) demandée')),
                ('regime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='scolarite.regimeetudes')),
                ('vague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='formations.refvague')),
                ('type_candidature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='admissions.typecandidature')),
                ('voie_acces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatures', to='admissions.voieacces')),
            ],
            options={
                'verbose_name': 'Admission – Candidature',
                'verbose_name_plural': 'Admission – Candidatures',
                'ordering': ['-date_candidature', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReglePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire', models.BooleanField(default=True)),
                ('ref_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles_pieces', to='formations.refformation', verbose_name='Formation (cycle)')),
                ('type_formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles_pieces', to='scolarite.typeformation')),
                ('type_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='admissions.typepiece')),
            ],
            options={
                'verbose_name': 'Admission – Règle de pièce',
                'verbose_name_plural': 'Admission – Règles de pièces',
                'ordering': ['type_piece__libelle'],
            },
        ),
        migrations.CreateModel(
            name='PieceCandidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire', models.BooleanField(default=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to=admissions.models.piece_upload_path)),
                ('numero_document', models.CharField(blank=True, max_length=100)),
                ('date_delivrance', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('MANQUANTE', 'Manquante'), ('FOURNIE', 'Fournie'), ('EN_VERIFICATION', 'En vérification'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('EXPIREE', 'Expirée')], default='MANQUANTE', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('verifie_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='admissions.candidature')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_verifiees', to=settings.AUTH_USER_MODEL)),
                ('type_piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces', to='admissions.typepiece')),
            ],
            options={
                'verbose_name': 'Admission – Pièce de candidature',
                'verbose_name_plural': 'Admission – Pièces de candidature',
                'ordering': ['type_piece__libelle'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('ADMIS_SOUS_RESERVE', 'Admis sous réserve'), ('EN_ATTENTE', 'En attente'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=30)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('reference_decision', models.CharField(blank=True, max_length=100)),
                ('date_limite_inscription', models.DateField(blank=True, help_text="Au-delà de cette date, l'admission ne permet plus de créer une inscription.", null=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='scolarite.anneeacademique')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='formations.refcategorie')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_decidees', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='formations.refgrade')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='scolarite.niveau', verbose_name="Niveau d'entrée")),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='scolarite.parcours')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='formations.refformation', verbose_name='Formation (cycle)')),
                ('vague', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='formations.refvague')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admissions.candidat')),
                ('candidature', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='admissions.candidature')),
                ('voie_acces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='admissions.voieacces')),
            ],
            options={
                'verbose_name': 'Admission – Admission',
                'verbose_name_plural': 'Admission – Admissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidat',
            index=models.Index(fields=['nom', 'prenom'], name='admissions__nom_419e92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reglepiece',
            unique_together={('type_piece', 'type_formation', 'ref_formation')},
        ),
        migrations.AddConstraint(
            model_name='piececandidature',
            constraint=models.UniqueConstraint(models.F('candidature'), models.F('type_piece'), name='uniq_piece_par_candidature_et_type'),
        ),
        migrations.AddIndex(
            model_name='candidature',
            index=models.Index(fields=['statut', 'annee_academique'], name='admissions__statut_53190a_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidature',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'ANNULE'), _negated=True), fields=('candidat', 'annee_academique', 'ref_formation', 'niveau'), name='uniq_candidature_active_par_candidat_formation_niveau'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['decision', 'annee_academique'], name='admissions__decisio_4b257d_idx'),
        ),
    ]
