# Generated by Django 5.1.4 on 2026-08-27 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CANDIDATURE_CREEE', 'Candidature créée'), ('CANDIDATURE_TRANSITION', 'Changement de statut de candidature'), ('PIECE_DEPOSEE', 'Pièce déposée'), ('PIECE_VERIFIEE', 'Pièce vérifiée'), ('ADMISSION_CREEE', 'Admission créée'), ('ADMISSION_DECISION', 'Décision d’admission'), ('ADMISSION_ANNULEE', 'Admission annulée'), ('INSCRIPTION_CREEE', 'Inscription administrative créée'), ('INSCRIPTION_TRANSITION', 'Changement de statut d’inscription'), ('MATRICULE_GENERE', 'Matricule généré'), ('INSCRIPTION_PEDAGOGIQUE_GENEREE', 'Inscriptions pédagogiques générées'), ('INSCRIPTION_PEDAGOGIQUE_MANUELLE', 'Modification pédagogique manuelle'), ('GROUPE_AFFECTATION', 'Affectation à un groupe'), ('GROUPE_CHANGEMENT', 'Changement de groupe'), ('REINSCRIPTION', 'Réinscription'), ('EVENEMENT_SCOLARITE', 'Événement de scolarité'), ('SYNCHRONISATION_EDT', 'Export vers l’emploi du temps')], max_length=50)),
                ('objet_type', models.CharField(blank=True, max_length=50)),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True)),
                ('objet_libelle', models.CharField(blank=True, max_length=255)),
                ('acteur_label', models.CharField(blank=True, max_length=150)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=255)),
                ('nouvelle_valeur', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_scolarite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Journal de scolarité',
                'verbose_name_plural': 'LMD – Journal de scolarité',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['objet_type', 'objet_id'], name='scolarite_j_objet_t_d4da67_idx'), models.Index(fields=['action', 'timestamp'], name='scolarite_j_action_611536_idx')],
            },
        ),
    ]
