# Generated by Django 5.1.4 on 2026-08-27 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0087_widen_grade_categorie_fields'),
        ('scolarite', '0003_dossieretudiant_inscriptionadministrative'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_enseignement', models.CharField(choices=[('CM', 'Cours magistral'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('STAGE', 'Stage'), ('AUTRE', 'Autre')], default='CM', max_length=10)),
                ('credits', models.PositiveSmallIntegerField(default=0, verbose_name='Crédits ECTS')),
                ('volume_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('statut', models.CharField(choices=[('PREVUE', 'Prévue'), ('VALIDEE', 'Validée'), ('ABANDONNEE', 'Abandonnée'), ('DISPENSEE', 'Dispensée')], default='PREVUE', max_length=20)),
                ('origine', models.CharField(choices=[('AUTOMATIQUE', 'Générée depuis la maquette'), ('MANUELLE', 'Ajout manuel')], default='AUTOMATIQUE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ecue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_pedagogiques', to='scolarite.ecue')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_pedagogiques', to='scolarite.groupe')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_pedagogiques', to='scolarite.inscriptionadministrative', verbose_name='Inscription administrative')),
                ('module_participant', models.ForeignKey(blank=True, help_text='Inscription au module opérationnel générée par la passerelle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_pedagogiques', to='formations.moduleparticipant')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_pedagogiques', to='scolarite.semestre')),
            ],
            options={
                'verbose_name': 'LMD – Inscription pédagogique',
                'verbose_name_plural': 'LMD – Inscriptions pédagogiques',
                'ordering': ['semestre__numero', 'ecue__ue__ordre', 'ecue__ordre'],
                'indexes': [models.Index(fields=['inscription', 'semestre'], name='scolarite_i_inscrip_504878_idx')],
                'constraints': [models.UniqueConstraint(fields=('inscription', 'ecue'), name='uniq_inscription_pedagogique_ecue')],
            },
        ),
    ]
