# Generated by Django 5.1.4 on 2026-09-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0007_alter_journalscolarite_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='cloturee',
            field=models.BooleanField(default=False, help_text="Une année clôturée n'accepte plus de nouvelle inscription."),
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='date_cloture',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evenementscolarite',
            name='type_evenement',
            field=models.CharField(choices=[('PASSAGE', 'Passage en année supérieure'), ('REDOUBLEMENT', 'Redoublement'), ('REPRISE', 'Reprise après suspension'), ('REORIENTATION', 'Changement de parcours'), ('CHANGEMENT_FORMATION', 'Changement de formation'), ('CHANGEMENT_GROUPE', 'Changement de groupe'), ('SUSPENSION', 'Suspension'), ('RADIATION', 'Radiation'), ('ABANDON', 'Abandon'), ('TRANSFERT', 'Transfert'), ('DIPLOMATION', 'Obtention du diplôme')], max_length=30),
        ),
    ]
