# Generated by Django 5.1.4 on 2026-09-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scolarite', '0008_anneeacademique_cloturee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenementscolarite',
            name='type_evenement',
            field=models.CharField(choices=[('PASSAGE', 'Passage en année supérieure'), ('REDOUBLEMENT', 'Redoublement'), ('REPRISE', 'Reprise après suspension'), ('REORIENTATION', 'Changement de parcours'), ('CHANGEMENT_FORMATION', 'Changement de formation'), ('CHANGEMENT_GROUPE', 'Changement de groupe'), ('SUSPENSION', 'Suspension'), ('RADIATION', 'Radiation'), ('EQUIVALENCE_DISPENSE', 'Équivalence ou dispense appliquée'), ('ABANDON', 'Abandon'), ('TRANSFERT', 'Transfert'), ('DIPLOMATION', 'Obtention du diplôme')], max_length=30),
        ),
    ]
