# Generated by Django 5.1.4 on 2026-09-07 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0089_formateur_fonction_formateur_grade_ref_and_more'),
        ('scolarite', '0009_alter_evenementscolarite_type_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndisponibiliteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='formations.formateur')),
            ],
            options={
                'verbose_name': 'LMD – Indisponibilité d’enseignant',
                'verbose_name_plural': 'LMD – Indisponibilités d’enseignants',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='AffectationPedagogique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_enseignement', models.CharField(choices=[('CM', 'Cours magistral'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('STAGE', 'Stage'), ('AUTRE', 'Autre')], default='CM', max_length=10)),
                ('volume_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('VALIDEE', 'Validée'), ('PLANIFIEE', 'Planifiée'), ('REALISEE', 'Réalisée'), ('ANNULEE', 'Annulée')], default='PROPOSEE', max_length=15)),
                ('observations', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_pedagogiques', to='scolarite.anneeacademique')),
                ('ecue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_pedagogiques', to='scolarite.ecue')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_pedagogiques', to='formations.formateur')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_pedagogiques', to='scolarite.groupe')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_pedagogiques', to='scolarite.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_pedagogiques', to='scolarite.parcours')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_pedagogiques', to='formations.refformation')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_pedagogiques', to='scolarite.semestre')),
                ('ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations_pedagogiques', to='scolarite.ue')),
            ],
            options={
                'verbose_name': 'LMD – Affectation pédagogique',
                'verbose_name_plural': 'LMD – Affectations pédagogiques',
                'ordering': ['semestre__numero', 'ecue__ue__ordre', 'ecue__ordre'],
                'indexes': [models.Index(fields=['annee_academique', 'enseignant'], name='scolarite_a_annee_a_26e597_idx'), models.Index(fields=['ecue', 'statut'], name='scolarite_a_ecue_id_063694_idx')],
            },
        ),
    ]
