# Generated by Django 6.0.3 on 2026-03-22 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0007_add_suspendue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionformation',
            name='heure_debut_prevue',
            field=models.TimeField(blank=True, help_text='Heure de début prévue', null=True),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='heure_fin_prevue',
            field=models.TimeField(blank=True, help_text='Heure de fin prévue', null=True),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='intitule',
            field=models.CharField(blank=True, default='', help_text='Intitulé libre (ex: Matin, Après-midi, Module 3…)', max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionformation',
            name='demarree_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionformation',
            name='demarree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_demarrees', to=settings.AUTH_USER_MODEL),
        ),
    ]
