# Generated by Django 6.0.3 on 2026-03-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0008_session_planning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionformation',
            name='auto_demarrage',
            field=models.BooleanField(default=False, help_text="Démarrer automatiquement à l'heure prévue"),
        ),
    ]
