# Generated by Django 6.0.3 on 2026-03-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0010_formateur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Séance liée à ce QR code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='formations.sessionformation'),
        ),
    ]
