# Generated by Django 6.0.3 on 2026-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0013_secretariat_and_participant_secretariat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionformation',
            name='auto_demarrage',
            field=models.BooleanField(default=True, help_text="Démarrer automatiquement à l'heure prévue"),
        ),
    ]
