# Generated by Django 5.1.4 on 2026-03-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0014_auto_demarrage_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretariat',
            name='type',
            field=models.CharField(blank=True, choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C')], default='', help_text='Type de secrétariat (A, B ou C)', max_length=1),
        ),
    ]
