# Generated by Django 5.1.4 on 2026-04-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0016_formateur_secretariats_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='grade_groupe',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='libelle_concours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='salle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='site',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='telephone2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='type_concours',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
