# Generated by Django 5.1.4 on 2026-04-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0019_add_vague_to_formation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionformation',
            options={'ordering': ['date_journee', 'heure_debut_prevue', 'numero'], 'verbose_name': 'Session de formation', 'verbose_name_plural': 'Sessions de formation'},
        ),
    ]
