# Generated by Django 5.1.4 on 2026-04-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0020_audit_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='titre',
            new_name='formation',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='cours',
            new_name='module',
        ),
    ]
