# Generated by Django 5.1.4 on 2026-04-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0021_rename_titre_to_formation_cours_to_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='lieu',
        ),
        migrations.AddField(
            model_name='formation',
            name='batiment',
            field=models.CharField(blank=True, default='', help_text='Bâtiment', max_length=255),
        ),
        migrations.AddField(
            model_name='formation',
            name='centre',
            field=models.CharField(blank=True, default='', help_text='Centre de formation', max_length=255),
        ),
        migrations.AddField(
            model_name='formation',
            name='salle',
            field=models.CharField(blank=True, default='', help_text='Salle', max_length=100),
        ),
    ]
