# Generated by Django 5.1.4 on 2026-04-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0022_remove_lieu_add_centre_batiment_salle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='centre',
            new_name='site',
        ),
    ]
