# Generated by Django 5.1.4 on 2026-04-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0024_remove_centre_formation_from_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='concours',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='corps',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='vague',
        ),
    ]
