# Generated by Django 5.1.4 on 2026-04-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0026_add_email_to_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='numero_module',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='objectif',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='programme',
        ),
        migrations.AddField(
            model_name='formation',
            name='numero_formation',
            field=models.PositiveSmallIntegerField(blank=True, help_text='N° de la formation dans le cycle', null=True),
        ),
    ]
