# Generated by Django 5.1.4 on 2026-04-13 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0029_add_ref_categorie_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='numero',
            new_name='matricule',
        ),
    ]
