# Generated by Django 5.1.4 on 2026-04-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0031_refmodule_link_refformation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='refmodule',
            unique_together=set(),
        ),
    ]
