# Generated by Django 5.1.4 on 2026-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0032_refmodule_remove_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='grade',
            field=models.CharField(help_text='Grade (A4, A3…)', max_length=20),
        ),
    ]
