# Generated by Django 5.1.4 on 2026-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0033_formation_grade_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='categorie',
            field=models.CharField(help_text='Catégorie (A, B, C…)', max_length=10),
        ),
    ]
