# Generated by Django 5.1.4 on 2026-04-13 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0035_formation_module_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(help_text='Intitulé du module/cours', max_length=255)),
                ('duree_prevue_heures', models.DecimalField(decimal_places=2, default=0, help_text='Volume horaire prévu pour ce module', max_digits=6)),
                ('ordre', models.PositiveSmallIntegerField(default=1, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['ordre', 'intitule'],
                'unique_together': {('formation', 'intitule')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessionformation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Module auquel appartient cette séance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.module'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionformation',
            unique_together={('formation', 'module', 'date_journee', 'numero')},
        ),
    ]
