# Generated by Django 5.1.4 on 2026-04-13 23:51

from django.db import migrations


def migrate_module_data(apps, schema_editor):
    Formation = apps.get_model('formations', 'Formation')
    Module = apps.get_model('formations', 'Module')
    SessionFormation = apps.get_model('formations', 'SessionFormation')

    for formation in Formation.objects.all():
        intitule = (formation.module or '').strip() or formation.formation
        module_obj, _ = Module.objects.get_or_create(
            formation=formation,
            intitule=intitule,
            defaults={'duree_prevue_heures': formation.duree_prevue_heures, 'ordre': 1},
        )
        SessionFormation.objects.filter(formation=formation, module__isnull=True).update(
            module=module_obj
        )


def reverse_migrate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0036_add_module_model'),
    ]

    operations = [
        migrations.RunPython(migrate_module_data, reverse_migrate),
    ]
