# Generated by Django 5.1.4 on 2026-04-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0038_remove_formation_module_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Auditeur', 'verbose_name_plural': 'Auditeurs'},
        ),
        migrations.AddField(
            model_name='participant',
            name='vague',
            field=models.CharField(blank=True, default='', help_text='Vague (PREMIERE VAGUE, DEUXIEME VAGUE…)', max_length=50),
        ),
    ]
