# Generated by Django 5.1.4 on 2026-04-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0040_alter_formateur_numero_alter_participant_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='batiment',
            field=models.CharField(blank=True, default='', help_text='Bâtiment', max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='date_debut',
            field=models.DateField(blank=True, help_text='Date de début du module', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin du module', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='formateur',
            field=models.ForeignKey(blank=True, help_text='Formateur principal du module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='formations.formateur'),
        ),
        migrations.AddField(
            model_name='module',
            name='salle',
            field=models.CharField(blank=True, default='', help_text='Salle', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='site',
            field=models.CharField(blank=True, default='', help_text='Centre de formation', max_length=255),
        ),
        migrations.AddField(
            model_name='module',
            name='statut',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminée')], default='PLANIFIEE', max_length=20),
        ),
    ]
