# Generated by Django 5.1.4 on 2026-04-15 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0043_replace_formationparticipant_with_moduleparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFormateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrit_le', models.DateTimeField(auto_now_add=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_assignes', to='formations.formateur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_formateurs', to='formations.module')),
            ],
            options={
                'verbose_name': 'Formateur assigné',
                'verbose_name_plural': 'Formateurs assignés',
                'unique_together': {('module', 'formateur')},
            },
        ),
        migrations.DeleteModel(
            name='FormationFormateur',
        ),
    ]
