# Generated by Django 5.1.4 on 2026-04-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0044_replace_formationformateur_with_moduleformateur'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionformation',
            unique_together={('module', 'date_journee', 'numero')},
        ),
        migrations.AlterField(
            model_name='sessionformation',
            name='module',
            field=models.ForeignKey(default=8, help_text='Module auquel appartient cette séance', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.module'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='sessionformation',
            name='formation',
        ),
    ]
