# Generated by Django 5.1.4 on 2026-04-16 00:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0047_module_add_grade_groupe_vague_secretariat'),
        ('presences', '0010_remove_formation_fk_from_pointage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionFormation',
            new_name='SessionModule',
        ),
    ]
