# Generated by Django 5.1.4 on 2026-04-18 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0054_rename_formateur_numero_to_numerobadge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='duree_prevue_heures',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Volume horaire prévu pour ce module', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='secretariat',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CHEF_SECRETARIAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretariats_resp', to=settings.AUTH_USER_MODEL),
        ),
    ]
