# Generated by Django 5.1.4 on 2026-06-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0076_module_add_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefModuleVolumeHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_horaire', models.DecimalField(blank=True, decimal_places=2, help_text='Volume horaire pour cette catégorie (en heures)', max_digits=6, null=True)),
                ('categorie', models.ForeignKey(help_text='Catégorie concernée (A, B, C, D...)', on_delete=django.db.models.deletion.CASCADE, related_name='volumes_horaires_modules', to='formations.refcategorie')),
                ('module', models.ForeignKey(help_text='Module du référentiel', on_delete=django.db.models.deletion.CASCADE, related_name='volumes_horaires', to='formations.refmodule')),
            ],
            options={
                'verbose_name': 'Référentiel – Volume horaire par catégorie',
                'verbose_name_plural': 'Référentiel – Volumes horaires par catégorie',
                'ordering': ['module', 'categorie__libelle'],
                'unique_together': {('module', 'categorie')},
            },
        ),
    ]
