# Generated by Django 5.1.4 on 2026-08-29 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0087_widen_grade_categorie_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
    ]
