# Generated by Django 5.1.4 on 2026-09-07 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0088_alter_participant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='fonction',
            field=models.CharField(blank=True, default='', help_text='Fonction administrative (ex : Chef de département).', max_length=100),
        ),
        migrations.AddField(
            model_name='formateur',
            name='grade_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formateurs_lmd', to='formations.refgrade', verbose_name='Grade (référentiel)'),
        ),
        migrations.AddField(
            model_name='formateur',
            name='statut_enseignant',
            field=models.CharField(blank=True, default='', help_text="Statut de l'enseignant (ex : Titulaire, Vacataire, Contractuel).", max_length=100),
        ),
    ]
