# Generated by Django 5.1.4 on 2026-09-07 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0089_formateur_fonction_formateur_grade_ref_and_more'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refsalle',
            name='type_espace',
            field=models.ForeignKey(blank=True, help_text="Type d'espace sportif (gymnase, piscine, terrain…).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salles', to='referentiels.reftypeespacesportif'),
        ),
    ]
