# Generated by Django 5.1.4 on 2026-09-07 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0090_refsalle_type_espace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodule',
            name='statut_validation',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée')], default='BROUILLON', help_text='Statut du workflow de validation : BROUILLON → SOUMISE → VALIDEE. Une note VALIDEE est verrouillée et ne peut plus être modifiée directement : seule une correction auditée (avec motif) est possible.', max_length=12),
        ),
        migrations.AddField(
            model_name='notemodule',
            name='validation_le',
            field=models.DateTimeField(blank=True, help_text='Horodatage de la validation/verrouillage.', null=True),
        ),
        migrations.AddField(
            model_name='notemodule',
            name='validation_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant validé (verrouillé) la note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_modules_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notemodule',
            name='verrouillee',
            field=models.BooleanField(default=False, help_text="True dès que la note est VALIDEE (verrouillée). Une note verrouillée n'est plus modifiable directement."),
        ),
        migrations.CreateModel(
            name='CorrectionNoteModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nouvelle_valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('motif', models.TextField(help_text='Motif obligatoire de la correction.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_notes_modules', to=settings.AUTH_USER_MODEL)),
                ('colonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='formations.notemodulecolonne')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_notes', to='formations.module')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='formations.notemodule')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_notes_modules', to='formations.participant')),
            ],
            options={
                'verbose_name': 'Correction de note module',
                'verbose_name_plural': 'Corrections de notes modules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'created_at'], name='formations__module__dce44f_idx'), models.Index(fields=['colonne', 'participant'], name='formations__colonne_6a1311_idx')],
            },
        ),
    ]
