# Generated by Django 5.1.4 on 2026-04-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
        ('formations', '0015_add_type_to_secretariat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secretariat',
            field=models.ForeignKey(blank=True, help_text='Secrétariat auquel appartient cet utilisateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='formations.secretariat'),
        ),
    ]
