# Generated by Django 5.1.4 on 2026-08-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_user_custom_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('DIRECTION', 'Direction'), ('CHEF_CPFAE_ADMIN', 'Chef INJS Admin'), ('CPFAE_ADMIN', 'INJS Admin'), ('CHEF_SECRETARIAT', 'Chef Secrétariat'), ('SECRETARIAT', 'Secrétariat'), ('FINANCE', 'Finance'), ('ARCHIVE', 'Archiviste'), ('ENCADRANT', 'Encadrant'), ('SUPERVISEUR', 'Superviseur'), ('FORMATEUR', 'Formateur'), ('AUDITEUR', 'Étudiant')], default='AUDITEUR', max_length=30),
        ),
    ]
