# Generated by Django 5.1.4 on 2026-09-15 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edts', '0001_init'),
        ('formations', '0092_refsalle_sqlite_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationcreneau',
            name='formateur',
            field=models.ForeignKey(blank=True, help_text='Formateur de référence (socle INJS-LMD) pour la détection de surcharges.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edt_affectations', to='formations.formateur'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='semaine_debut',
            field=models.PositiveSmallIntegerField(default=1, help_text='Numéro de semaine académique de début (1-based).'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='semaine_fin',
            field=models.PositiveSmallIntegerField(default=36, help_text='Numéro de semaine académique de fin (bornes de planification).'),
        ),
    ]
