# Generated by Django 5.1.4 on 2026-09-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edts', '0002_affectationcreneau_formateur_and_more'),
        ('scolarite', '0015_alter_journalscolarite_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationcreneau',
            name='affectation_pedagogique',
            field=models.ForeignKey(blank=True, help_text="Contexte pédagogique de la séance (formation, parcours, niveau, semestre, UE, ECUE, groupe, enseignant). Rattachement MANUEL et explicite : aucune déduction automatique n'est effectuée.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_edt', to='scolarite.affectationpedagogique'),
        ),
    ]
