# Generated by Django 5.1.4 on 2026-09-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edts', '0003_affectationcreneau_affectation_pedagogique'),
        ('formations', '0095_formation_ref_formation_refformation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationcreneau',
            name='salle',
            field=models.ForeignKey(blank=True, help_text="Salle du référentiel INJS (Lot L2). Complète `salle_nom`, conservé en lecture/transition : le rattachement est MANUEL et explicite, aucune déduction automatique n'est effectuée.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seances_edt', to='formations.refsalle'),
        ),
    ]
