# Generated by Django 5.1.4 on 2026-09-28 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edts', '0004_affectationcreneau_salle'),
        ('formations', '0097_alter_refsalle_type_lieu'),
        ('scolarite', '0015_alter_journalscolarite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], db_index=True, max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible'), ('PREFERENCE', 'Préférence')], db_index=True, default='INDISPONIBLE', max_length=15)),
                ('motif', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EDT – Disponibilité horaire',
                'verbose_name_plural': 'EDT – Disponibilités horaires',
                'ordering': ['jour', 'heure_debut', 'heure_fin'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='emploidutemps',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='empreinte',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 des paramètres de génération (année, formation, parcours, niveau, semestre, groupes, maquette, version).', max_length=64),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='motif_modification',
            field=models.CharField(blank=True, default='', help_text='Motif de la version courante (ex. « ajout salle TP Marcory »).', max_length=255),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='publie_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='publie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edt_publies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='valide_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edt_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='version',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text="Version de l'EDT pour ce périmètre (V1, V2, V3…). Une nouvelle version se crée par clonage, jamais par écrasement."),
        ),
        migrations.AlterField(
            model_name='conflitcreneau',
            name='type_conflit',
            field=models.CharField(choices=[('HORAIRE_ENSEIGNANT', 'Chevauchement enseignant'), ('HORAIRE_GROUPETUDIANT', 'Chevauchement groupe/étudiant'), ('HORAIRE_SALLE', 'Chevauchement salle'), ('HORAIRE_MODULE', 'Chevauchement module'), ('CAPACITE', 'Capacité de salle insuffisante'), ('COMPATIBILITE_SALLE', 'Salle incompatible avec le type d’enseignement'), ('HORS_CALENDRIER', 'Séance hors période autorisée'), ('DISPONIBILITE', 'Indisponibilité enseignant ou salle'), ('MANUEL', 'Signalé manuellement')], db_index=True, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='emploidutemps',
            unique_together={('annee_academique', 'population_type', 'population_id', 'version')},
        ),
        migrations.AddIndex(
            model_name='emploidutemps',
            index=models.Index(fields=['empreinte'], name='edts_emploi_emprein_9023c0_idx'),
        ),
        migrations.AddField(
            model_name='disponibilitehoraire',
            name='annee_academique',
            field=models.ForeignKey(help_text='Année concernée : les disponibilités sont annuelles.', on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_horaires', to='scolarite.anneeacademique'),
        ),
        migrations.AddField(
            model_name='disponibilitehoraire',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_horaires', to='formations.formateur'),
        ),
        migrations.AddField(
            model_name='disponibilitehoraire',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_horaires', to='formations.refsalle'),
        ),
        migrations.AddIndex(
            model_name='disponibilitehoraire',
            index=models.Index(fields=['annee_academique', 'jour', 'heure_debut'], name='edts_dispon_annee_a_bffc0a_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilitehoraire',
            index=models.Index(fields=['enseignant', 'annee_academique', 'statut'], name='edts_dispon_enseign_5c08a4_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilitehoraire',
            index=models.Index(fields=['salle', 'annee_academique', 'statut'], name='edts_dispon_salle_i_5f4dc9_idx'),
        ),
        migrations.AddConstraint(
            model_name='disponibilitehoraire',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('enseignant__isnull', False), ('salle__isnull', True)), models.Q(('enseignant__isnull', True), ('salle__isnull', False)), _connector='OR'), name='dispo_horaire_un_seul_porteur'),
        ),
        migrations.AddConstraint(
            model_name='disponibilitehoraire',
            constraint=models.CheckConstraint(condition=models.Q(('heure_fin__gt', models.F('heure_debut'))), name='dispo_horaire_plage_valide'),
        ),
    ]
