# Generated by Django 5.1.4 on 2026-10-05 03:08

from datetime import datetime

from django.db import migrations, models


def _minute(valeur):
    """Ramène une ``time`` à la granularité métier (minute), sans secondes."""
    if valeur is None:
        return None
    return datetime(2000, 1, 1, valeur.hour, valeur.minute).time()


def normaliser_horaires(apps, schema_editor):
    """Normalise les horaires existants AVANT la pose de la contrainte.

    Un créneau est un repère d'agenda : ses heures sont arrondies à la minute.
    Sans cette étape, deux lignes déjà présentes (ex. 02:22:00.80 et 02:22:59.20)
    tomberaient sur le même couple arrondi et la contrainte échouerait.
    """
    CreneauTemplate = apps.get_model('edts', 'CreneauTemplate')
    for creneau in CreneauTemplate.objects.all().iterator():
        debut, fin = _minute(creneau.heure_debut), _minute(creneau.heure_fin)
        if debut == creneau.heure_debut and fin == creneau.heure_fin:
            continue
        creneau.heure_debut, creneau.heure_fin = debut, fin
        creneau.save(update_fields=['heure_debut', 'heure_fin'])


class Migration(migrations.Migration):

    dependencies = [
        ('edts', '0005_disponibilitehoraire_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=normaliser_horaires,
            # Retour arrière impossible : la granularité à la seconde est perdue
            # et n'est pas une donnée métier. Migration volontairement irreversible.
            reverse_code=None,
            elidable=True,
        ),
        migrations.AddConstraint(
            model_name='creneautemplate',
            constraint=models.UniqueConstraint(fields=('jour', 'heure_debut', 'heure_fin'), name='uniq_creneau_template_jour_horaires', violation_error_message='Ce créneau horaire existe déjà pour ce jour : un créneau identique (jour, début, fin) ne peut être créé deux fois.'),
        ),
    ]
