# Generated by Django 5.1.4 on 2026-09-08 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0091_lot1_notes_workflow'),
        ('jurys', '0002_notificationjury'),
        ('scolarite', '0013_alter_journalscolarite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mention', models.CharField(blank=True, default='', max_length=30)),
                ('credits_acquis', models.PositiveSmallIntegerField(default=0)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDATION_PENDING', 'En attente de validation'), ('VALIDATED', 'Validé'), ('REVOKED', 'Révoqué')], default='BROUILLON', max_length=20)),
                ('pdf_fichier', models.FileField(blank=True, max_length=300, null=True, upload_to='graduation/diplomes/')),
                ('empreinte_pdf', models.CharField(blank=True, default='', max_length=64)),
                ('motif_revocation', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_revocation', models.DateTimeField(blank=True, null=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='scolarite.anneeacademique')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes_crees', to=settings.AUTH_USER_MODEL)),
                ('decision_jury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='jurys.decisionjury')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='scolarite.dossieretudiant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='scolarite.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='scolarite.parcours')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='formations.refformation')),
                ('revoque_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes_revoques', to=settings.AUTH_USER_MODEL)),
                ('session_jury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diplomes', to='jurys.sessionjury')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Diplôme',
                'verbose_name_plural': 'LMD – Diplômes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DIPLOME', 'Diplôme'), ('ATTESTATION', 'Attestation'), ('CERTIFICAT', 'Certificat'), ('RELEVE_NOTES', 'Relevé de notes')], max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('modele_pdf', models.FileField(blank=True, max_length=300, null=True, upload_to='graduation/modeles/')),
                ('actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(blank=True, help_text='NULL = gabarit global par défaut.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modeles_document', to='formations.refformation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_document_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Modèle de document',
                'verbose_name_plural': 'LMD – Modèles de document',
                'ordering': ['type', 'formation__intitule', '-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Reedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(help_text='Motif obligatoire de la réédition.')),
                ('pdf_fichier', models.FileField(blank=True, max_length=300, null=True, upload_to='graduation/reeditions/')),
                ('empreinte_pdf', models.CharField(blank=True, default='', max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reeditions', to='graduation.diplome')),
                ('par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomes_reedits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Réédition de diplôme',
                'verbose_name_plural': 'LMD – Rééditions de diplôme',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RegistreDiplomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloture', models.BooleanField(default=False)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registre_diplomes', to='scolarite.anneeacademique')),
                ('cloture_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registres_clotures', to=settings.AUTH_USER_MODEL)),
                ('diplomes', models.ManyToManyField(blank=True, related_name='registres', to='graduation.diplome')),
            ],
            options={
                'verbose_name': 'LMD – Registre des diplômes',
                'verbose_name_plural': 'LMD – Registres des diplômes',
                'ordering': ['-annee_academique__libelle'],
            },
        ),
        migrations.AddConstraint(
            model_name='diplome',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'VALIDATED')), fields=('etudiant', 'ref_formation', 'niveau'), name='uniq_diplome_par_etudiant_formation_niveau', violation_error_message="Un même étudiant ne peut recevoir qu'un seul diplôme VALIDÉ pour la même formation et le même niveau."),
        ),
        migrations.AddConstraint(
            model_name='modeledocument',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('type', 'formation'), name='uniq_modele_par_type_formation'),
        ),
        migrations.AddConstraint(
            model_name='modeledocument',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True), ('formation__isnull', True)), fields=('type',), name='uniq_modele_global_par_type'),
        ),
    ]
