# Generated by Django 5.1.4 on 2026-09-08 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('ENTRANT', 'Entrant'), ('SORTANT', 'Sortant')], max_length=10)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('objet', models.CharField(max_length=255)),
                ('expediteur', models.CharField(blank=True, default='', max_length=255)),
                ('destinataire', models.CharField(blank=True, default='', max_length=255)),
                ('date_courrier', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, upload_to='administrations/courriers/')),
                ('statut', models.CharField(choices=[('RECU', 'Reçu'), ('EN_COURS', 'En cours de traitement'), ('REPONDU', 'Répondu'), ('CLASSE', 'Classé'), ('ARCHIVE', 'Archivé')], default='RECU', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Courrier',
                'verbose_name_plural': 'LMD – Courriers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('NOTE_SERVICE', 'Note de service'), ('ARRETE', 'Arrêté'), ('DECISION', 'Décision'), ('CIRCULAIRE', 'Circulaire'), ('AUTRE', 'Autre')], default='NOTE_SERVICE', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField(blank=True, default='')),
                ('document_pdf', models.FileField(blank=True, upload_to='administrations/documents/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_VALIDATION', 'En validation'), ('SIGNE', 'Signé'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL)),
                ('signe_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_signes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Document officiel',
                'verbose_name_plural': 'LMD – Documents officiels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PROPOSEE', max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motif_refus', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Mission',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReunionCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_reunion', models.CharField(max_length=150)),
                ('titre', models.CharField(max_length=255)),
                ('date_reunion', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, default='', max_length=255)),
                ('ordre_du_jour', models.TextField(blank=True, default='')),
                ('pv_contenu', models.TextField(blank=True, default='')),
                ('pv_fichier', models.FileField(blank=True, upload_to='administrations/reunions/pv/')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('TENUE', 'Tenue'), ('PV_EMIS', 'PV émis'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='reunions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Réunion / Commission',
                'ordering': ['-date_reunion'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField(default=1)),
                ('contenu', models.TextField(blank=True, default='')),
                ('fichier', models.FileField(blank=True, upload_to='administrations/documents_versions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='administrations.documentofficiel')),
            ],
            options={
                'ordering': ['numero_version'],
                'unique_together': {('document', 'numero_version')},
            },
        ),
    ]
