# Generated by Django 6.0.3 on 2026-03-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp_entree', models.DateTimeField()),
                ('timestamp_sortie', models.DateTimeField(blank=True, null=True)),
                ('duree_presence_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours (en salle)'), ('TERMINE', 'Terminé'), ('FORCE_DFRC', 'Forcé par DFRC')], default='EN_COURS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='formations.formation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='formations.participant')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-timestamp_entree'],
                'unique_together': {('participant', 'formation')},
            },
        ),
    ]
