# Generated by Django 6.0.3 on 2026-03-17 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_alter_participant_numero'),
        ('presences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointage',
            options={'ordering': ['-date_journee', '-timestamp_entree'], 'verbose_name': 'Pointage', 'verbose_name_plural': 'Pointages'},
        ),
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pointage',
            name='date_journee',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together={('participant', 'formation', 'date_journee')},
        ),
    ]
