# Generated by Django 6.0.3 on 2026-03-19 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_formateur_formationformateur'),
        ('presences', '0003_alter_pointage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='formations.formateur'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='formations.participant'),
        ),
    ]
