# Generated by Django 5.1.4 on 2026-04-09 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0020_audit_log'),
        ('presences', '0006_pointage_session_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SCAN_ENTREE', 'Scan entrée (QR public)'), ('SCAN_SORTIE', 'Scan sortie (QR public)'), ('SCAN_SECURE_ENTREE', 'Scan sécurisé entrée (mobile)'), ('SCAN_SECURE_SORTIE', 'Scan sécurisé sortie (mobile)'), ('FORCE_ENTREE', 'Entrée forcée (encadrant/DFRC)'), ('FORCE_SORTIE', 'Sortie forcée (encadrant/DFRC)'), ('CLOSE_SESSION', 'Fermeture de session (encadrant/DFRC)'), ('DEVICE_UNBIND', 'Déliaison appareil')], max_length=30)),
                ('acteur_label', models.CharField(blank=True, default='', help_text="Nom de l'acteur au moment de l'action (dénormalisé)", max_length=255)),
                ('cible_type', models.CharField(blank=True, default='', help_text="'participant' ou 'formateur'", max_length=20)),
                ('cible_numero', models.CharField(blank=True, default='', max_length=50)),
                ('cible_nom', models.CharField(blank=True, default='', max_length=255)),
                ('formation_titre', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=255)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires libres')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acteur', models.ForeignKey(blank=True, help_text="Utilisateur connecté ayant réalisé l'action (null si scan public)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='formations.formation')),
                ('pointage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='presences.pointage')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', 'timestamp'], name='presences_a_action_a22b92_idx'), models.Index(fields=['acteur', 'timestamp'], name='presences_a_acteur__a026cf_idx'), models.Index(fields=['cible_numero', 'timestamp'], name='presences_a_cible_n_0e4af5_idx')],
            },
        ),
    ]
