# Generated by Django 5.1.4 on 2026-07-07 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0085_notificationfinanceajustement'),
        ('presences', '0021_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SCAN_ENTREE', 'Scan entrée (QR public)'), ('SCAN_SORTIE', 'Scan sortie (QR public)'), ('SCAN_SECURE_ENTREE', 'Scan sécurisé entrée (mobile)'), ('SCAN_SECURE_SORTIE', 'Scan sécurisé sortie (mobile)'), ('FORCE_ENTREE', 'Entrée forcée (encadrant/DFRC)'), ('FORCE_SORTIE', 'Sortie forcée (encadrant/DFRC)'), ('CLOSE_SESSION', 'Fermeture de session (encadrant/DFRC)'), ('AUTO_ABSENT', 'Absent automatique (délai badge sortie dépassé)'), ('SCAN_HEARTBEAT', 'Heartbeat mobile géolocalisé'), ('NO_HEARTBEAT', 'Alerte absence heartbeat mobile'), ('OUT_OF_GEOFENCE', 'Sortie du périmètre géographique'), ('AUTO_EXIT', 'Sortie automatique (heartbeat/geofence)'), ('DEVICE_UNBIND', 'Déliaison appareil'), ('FORMATION_CREATE', 'Création de formation'), ('FORMATION_UPDATE', 'Modification de formation'), ('FORMATION_DELETE', 'Suppression de formation'), ('FORMATION_STATUT', 'Changement de statut de formation'), ('FORMATION_ASSIGN_SUPERVISEUR', 'Assignation superviseur'), ('MODULE_ASSIGN_SUPERVISEUR', 'Assignation encadrant à un module'), ('MODULE_CREATE', 'Création de module'), ('MODULE_UPDATE', 'Modification de module'), ('MODULE_DELETE', 'Suppression de module'), ('MODULE_ARCHIVE', 'Archivage de module'), ('FORMATION_QR_GENERATE', 'Génération QR code'), ('SEANCE_CREATE', 'Création de séance'), ('SEANCE_START', 'Démarrage de séance'), ('SEANCE_STOP', 'Arrêt de séance'), ('SEANCE_UPDATE', 'Modification de séance'), ('SEANCE_DELETE', 'Suppression de séance'), ('SEANCE_IMPORT', 'Import séances (Excel)'), ('PARTICIPANT_CREATE', "Création d'auditeur"), ('PARTICIPANT_UPDATE', "Modification d'auditeur"), ('PARTICIPANT_DELETE', "Suppression d'auditeur"), ('PARTICIPANT_ADD_FORMATION', 'Inscription auditeur à formation'), ('PARTICIPANT_REMOVE_FORMATION', 'Désinscription auditeur de formation'), ('PARTICIPANT_IMPORT', 'Import auditeurs (Excel)'), ('RATTRAPAGE_CREATE', "Création d'un rattrapage inter-cohorte"), ('RATTRAPAGE_PRESENCE', 'Présence générée pour un rattrapage'), ('RATTRAPAGE_CANCEL', "Annulation d'un rattrapage"), ('FORMATEUR_CREATE', 'Création de formateur'), ('FORMATEUR_UPDATE', 'Modification de formateur'), ('FORMATEUR_DELETE', 'Suppression de formateur'), ('FORMATEUR_ADD_FORMATION', 'Assignation formateur à formation'), ('FORMATEUR_REMOVE_FORMATION', 'Retrait formateur de formation'), ('FORMATEUR_IMPORT', 'Import formateurs (Excel)'), ('USER_CREATE', "Création d'utilisateur"), ('USER_UPDATE', "Modification d'utilisateur"), ('USER_DELETE', "Suppression d'utilisateur"), ('USER_LOGIN', 'Connexion utilisateur'), ('USER_LOGOUT', 'Déconnexion utilisateur'), ('USER_PASSWORD_CHANGE', 'Changement de mot de passe'), ('SECRETARIAT_CREATE', 'Création de secrétariat'), ('SECRETARIAT_UPDATE', 'Modification de secrétariat'), ('SECRETARIAT_DELETE', 'Suppression de secrétariat'), ('REFERENTIEL_CREATE', 'Création référentiel'), ('REFERENTIEL_UPDATE', 'Modification référentiel'), ('REFERENTIEL_DELETE', 'Suppression référentiel'), ('IMPORT_EXCEL', 'Import Excel global'), ('FINANCE_AJUSTEMENT_PROPOSE', 'Proposition ajustement horaire finance'), ('FINANCE_AJUSTEMENT_VALIDE', 'Validation ajustement horaire finance'), ('FINANCE_AJUSTEMENT_REJETE', 'Rejet ajustement horaire finance'), ('FINANCE_SETTINGS_UPDATE', 'Modification paramètres finance')], max_length=40),
        ),
        migrations.CreateModel(
            name='Rattrapage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EFFECTUE', 'Effectué'), ('ANNULE', 'Annulé')], db_index=True, default='PLANIFIE', max_length=10)),
                ('motif', models.CharField(blank=True, default='', help_text='Motif du rattrapage (ex. absence justifiée, chevauchement…)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rattrapages_crees', to=settings.AUTH_USER_MODEL)),
                ('module_origine', models.ForeignKey(blank=True, help_text="Module de la cohorte d'origine (cours manqué). Optionnel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rattrapages_origine', to='formations.module')),
                ('participant', models.ForeignKey(help_text='Auditeur qui effectue le rattrapage', on_delete=django.db.models.deletion.CASCADE, related_name='rattrapages', to='formations.participant')),
                ('pointage', models.OneToOneField(blank=True, help_text='Présence effectivement générée pour ce rattrapage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rattrapage', to='presences.pointage')),
                ('seance_manquee', models.ForeignKey(blank=True, help_text="Séance précise manquée par l'auditeur. Optionnel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rattrapages_manques', to='formations.sessionmodule')),
                ('seance_rattrapage', models.ForeignKey(help_text="Séance d'accueil (autre cohorte) où l'auditeur rattrape le cours", on_delete=django.db.models.deletion.CASCADE, related_name='rattrapages', to='formations.sessionmodule')),
            ],
            options={
                'verbose_name': 'Rattrapage',
                'verbose_name_plural': 'Rattrapages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['participant', 'statut'], name='presences_r_partici_e021ae_idx'), models.Index(fields=['seance_rattrapage', 'statut'], name='presences_r_seance__7edb12_idx')],
                'constraints': [models.UniqueConstraint(fields=('participant', 'seance_rattrapage'), name='uniq_rattrapage_participant_seance')],
            },
        ),
    ]
