# Generated by Django 5.1.4 on 2026-09-15 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edts', '0002_affectationcreneau_formateur_and_more'),
        ('presences', '0026_lot1_notes_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='seance_edt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='edts.affectationcreneau'),
        ),
    ]
