# Generated by Django 5.1.4 on 2026-09-15 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0094_qrtoken_seance_edt_alter_qrtoken_session'),
        ('presences', '0027_pointage_seance_edt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Séance liée à ce pointage (null pour une séance LMD badgée via QR EDT)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='formations.sessionmodule'),
        ),
    ]
