# Generated by Django 5.1.4 on 2026-09-15 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edts', '0002_affectationcreneau_formateur_and_more'),
        ('formations', '0095_formation_ref_formation_refformation_code_and_more'),
        ('presences', '0028_alter_pointage_session'),
        ('scolarite', '0015_alter_journalscolarite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationabsence',
            name='seance_edt',
            field=models.ForeignKey(blank=True, help_text="Séance d'origine de l'alerte (flux EDT/LMD uniquement).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_absence', to='edts.affectationcreneau', verbose_name='Séance LMD'),
        ),
        migrations.AddConstraint(
            model_name='notificationabsence',
            constraint=models.UniqueConstraint(condition=models.Q(('seance_edt__isnull', False)), fields=('destinataire', 'etudiant', 'seance_edt', 'niveau'), name='notif_absence_lmd_non_dupliquee'),
        ),
    ]
