# Generated by Django 5.1.4 on 2026-09-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LMD – Direction',
                'verbose_name_plural': 'LMD – Directions',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.ForeignKey(blank=True, help_text='Direction de rattachement (nullable : département autonome).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departements', to='administrations.direction')),
            ],
            options={
                'verbose_name': 'LMD – Département',
                'verbose_name_plural': 'LMD – Départements',
                'ordering': ['ordre', 'libelle'],
            },
        ),
    ]
