# Generated by Django 5.1.4 on 2026-09-15 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0002_direction_departement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='adjoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_adjointes', to=settings.AUTH_USER_MODEL, verbose_name='Adjoint(e)'),
        ),
        migrations.AddField(
            model_name='departement',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='departement',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Localisation (bâtiment, étage, porte)'),
        ),
        migrations.AddField(
            model_name='departement',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_pilotes', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='departement',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='direction',
            name='adjoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_adjointees', to=settings.AUTH_USER_MODEL, verbose_name='Adjoint(e)'),
        ),
        migrations.AddField(
            model_name='direction',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='direction',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Localisation (bâtiment, étage, porte)'),
        ),
        migrations.AddField(
            model_name='direction',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_pilotees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='direction',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
    ]
