# Generated by Django 5.2.15 on 2026-07-04 19:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='scheduled', max_length=15)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, max_length=50)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='defenses/reports/')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='students.student')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('normal', 'Session normale'), ('retake', 'Session de rattrapage')], default='normal', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_open', models.BooleanField(default=False)),
                ('results_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='academics.academicyear')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='academics.semester')),
            ],
            options={
                'unique_together': {('academic_year', 'semester', 'session_type')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('evaluation_type', models.CharField(choices=[('cc', 'Contrôle Continu'), ('exam', 'Examen'), ('tp', 'Travaux Pratiques'), ('project', 'Projet')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5)),
                ('date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course')),
                ('teaching_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.teachingunit')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='exams.examsession')),
            ],
            options={
                'ordering': ['teaching_unit', 'evaluation_type'],
            },
        ),
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('validated', 'Validée'), ('published', 'Publiée')], default='draft', max_length=15)),
                ('deliberation_date', models.DateTimeField(blank=True, null=True)),
                ('results_summary', models.JSONField(default=dict)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='academics.program')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='academics.promotion')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='exams.examsession')),
            ],
            options={
                'unique_together': {('exam_session', 'program', 'promotion')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_absent', models.BooleanField(default=False)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='exams.evaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'evaluation'], name='exams_grade_student_1d1862_idx')],
                'unique_together': {('student', 'evaluation')},
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='membre', max_length=50)),
                ('deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_members', to='exams.deliberation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('deliberation', 'member')},
            },
        ),
    ]
