# Generated by Django 5.1.4 on 2026-09-07 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0091_lot1_notes_workflow'),
        ('scolarite', '0012_alter_journalscolarite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_session', models.CharField(choices=[('NORMALE', 'Session normale'), ('RATTRAPAGE', 'Rattrapage'), ('RECTIFICATION', 'Rectification')], default='NORMALE', max_length=15)),
                ('statut', models.CharField(choices=[('PREPARATION', 'Préparation'), ('CONTROLE', 'Contrôle'), ('CALCUL', 'Calcul'), ('DELIBERATION', 'Délibération'), ('DECISION', 'Décision'), ('PV_GENERE', 'PV généré'), ('VALIDE', 'Validé'), ('VERROUILLE', 'Verrouillé'), ('PUBLIE', 'Publié')], default='PREPARATION', max_length=15)),
                ('libelle', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_jury', to='scolarite.anneeacademique')),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_jury_creees', to=settings.AUTH_USER_MODEL)),
                ('maquette', models.ForeignKey(help_text='Version de maquette verrouillée (VALIDEE/ACTIVE) supportant la délibération.', on_delete=django.db.models.deletion.PROTECT, related_name='sessions_jury', to='scolarite.maquette')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_jury', to='scolarite.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_jury', to='scolarite.parcours')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_jury', to='formations.refformation')),
                ('semestre', models.ForeignKey(blank=True, help_text='Null = jury annuel.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_jury', to='scolarite.semestre')),
            ],
            options={
                'verbose_name': 'LMD – Session de jury',
                'verbose_name_plural': 'LMD – Sessions de jury',
                'ordering': ['-annee_academique__libelle', 'niveau__ordre', 'type_session'],
            },
        ),
        migrations.CreateModel(
            name='PVJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(max_length=300, upload_to='jurys/pv/')),
                ('sha256', models.CharField(max_length=64)),
                ('genere_le', models.DateTimeField(auto_now_add=True)),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_jury_generes', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pv', to='jurys.sessionjury')),
            ],
            options={
                'verbose_name': 'LMD – PV de jury',
                'verbose_name_plural': 'LMD – PV de jury',
            },
        ),
        migrations.CreateModel(
            name='PropositionJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat', models.JSONField(help_text='Structure complète produite par le moteur ECTS.')),
                ('empreinte', models.CharField(help_text='SHA-256 du résultat (reproductibilité).', max_length=64)),
                ('decision_proposee', models.CharField(blank=True, default='', max_length=12)),
                ('credits_acquis', models.PositiveSmallIntegerField(default=0)),
                ('calcule_le', models.DateTimeField(auto_now_add=True)),
                ('calcule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_jury_calculees', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propositions_jury', to='scolarite.inscriptionadministrative')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propositions_jury', to='formations.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='jurys.sessionjury')),
            ],
            options={
                'verbose_name': 'LMD – Proposition de jury',
                'verbose_name_plural': 'LMD – Propositions de jury',
                'ordering': ['session', 'participant', '-calcule_le'],
            },
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(choices=[('PRESIDENT', 'Président'), ('SECRETAIRE', 'Secrétaire'), ('MEMBRE', 'Membre')], default='MEMBRE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_jury_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membres_jury', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='jurys.sessionjury')),
            ],
            options={
                'verbose_name': 'LMD – Membre de jury',
                'verbose_name_plural': 'LMD – Membres de jury',
                'ordering': ['session', 'fonction', 'user'],
            },
        ),
        migrations.CreateModel(
            name='DecisionJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('ADMIS_RESERVES', 'Admis avec réserves')], max_length=20)),
                ('credits_acquis', models.PositiveSmallIntegerField(default=0)),
                ('moyenne_generale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mention', models.CharField(blank=True, default='', max_length=20)),
                ('decision_manuelle', models.BooleanField(default=False, help_text='True si la décision diverge de la proposition du moteur.')),
                ('justification', models.TextField(blank=True, default='', help_text='Obligatoire pour toute décision manuelle.')),
                ('decide_le', models.DateTimeField(auto_now=True)),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_jury', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_jury', to='scolarite.inscriptionadministrative')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_jury', to='formations.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='jurys.sessionjury')),
            ],
            options={
                'verbose_name': 'LMD – Décision de jury',
                'verbose_name_plural': 'LMD – Décisions de jury',
                'ordering': ['session', 'participant__nom', 'participant__prenom'],
            },
        ),
        migrations.AddConstraint(
            model_name='sessionjury',
            constraint=models.UniqueConstraint(fields=('annee_academique', 'ref_formation', 'parcours', 'niveau', 'type_session'), name='uniq_session_jury_par_session'),
        ),
        migrations.AddIndex(
            model_name='propositionjury',
            index=models.Index(fields=['session', 'participant'], name='jurys_propo_session_0a7add_idx'),
        ),
        migrations.AddIndex(
            model_name='propositionjury',
            index=models.Index(fields=['empreinte'], name='jurys_propo_emprein_666bb6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membrejury',
            unique_together={('session', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='decisionjury',
            unique_together={('session', 'inscription')},
        ),
    ]
