# Generated by Django 6.0.3 on 2026-03-17 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('objectif', models.TextField(blank=True, default='')),
                ('lieu', models.CharField(blank=True, default='', max_length=255)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('duree_prevue_heures', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('programme', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='PLANIFIEE', max_length=20)),
                ('superviseur_assigne_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to=settings.AUTH_USER_MODEL)),
                ('superviseur', models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERVISEUR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_supervisees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('organisation', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='QRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('expire_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='formations.formation')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_tokens_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Token',
                'verbose_name_plural': 'QR Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrit_le', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_participants', to='formations.formation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_inscrites', to='formations.participant')),
            ],
            options={
                'verbose_name': 'Inscription formation',
                'verbose_name_plural': 'Inscriptions formations',
                'unique_together': {('formation', 'participant')},
            },
        ),
    ]
