# Generated by Django 6.0.3 on 2026-03-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_formateur_formationformateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='session_demarree_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='session_terminee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
