# Generated by Django 6.0.3 on 2026-03-20 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0004_formation_session_demarree_le_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_journee', models.DateField(default=django.utils.timezone.localdate)),
                ('numero', models.PositiveSmallIntegerField(help_text='Numéro de session dans la journée (1, 2, 3…)')),
                ('demarree_le', models.DateTimeField()),
                ('terminee_le', models.DateTimeField(blank=True, null=True)),
                ('demarree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_demarrees', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Session de formation',
                'verbose_name_plural': 'Sessions de formation',
                'ordering': ['date_journee', 'numero'],
                'unique_together': {('formation', 'date_journee', 'numero')},
            },
        ),
    ]
