# Generated by Django 6.0.3 on 2026-03-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0005_sessionformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='categorie',
            field=models.CharField(blank=True, default='', help_text='Catégorie (A, B, C…)', max_length=10),
        ),
        migrations.AddField(
            model_name='formation',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Grade (A4, A3…)', max_length=20),
        ),
        migrations.AddField(
            model_name='formation',
            name='numero_module',
            field=models.PositiveSmallIntegerField(blank=True, help_text='N° du module dans le cycle', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='categorie',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='centre_formation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='concours',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='corps',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='groupe',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='lieu_naissance',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='participant',
            name='matricule',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='sexe',
            field=models.CharField(blank=True, choices=[('MASCULIN', 'Masculin'), ('FEMININ', 'Féminin')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='participant',
            name='vague',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
