# Generated by Django 6.0.3 on 2026-03-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_formation_categorie_formation_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='statut',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminée')], default='PLANIFIEE', max_length=20),
        ),
    ]
