# Generated by Django 6.0.3 on 2026-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0011_qrtoken_session_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='cours',
            field=models.CharField(blank=True, default='', help_text='Cours', max_length=255),
        ),
    ]
