# Generated by Django 5.1.4 on 2026-04-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0017_add_participant_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='groupe',
            field=models.CharField(blank=True, default='', help_text='Groupe (GROUPE 1, GROUPE 2…)', max_length=50),
        ),
    ]
