# Generated by Django 5.1.4 on 2026-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0018_add_groupe_to_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='vague',
            field=models.CharField(blank=True, default='', help_text='Vague (PREMIERE VAGUE, DEUXIEME VAGUE…)', max_length=50),
        ),
    ]
