# Generated by Django 5.1.4 on 2026-04-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0023_rename_centre_to_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='centre_formation',
        ),
    ]
