# Generated by Django 5.1.4 on 2026-04-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0025_remove_fields_from_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
