# Generated by Django 5.1.4 on 2026-04-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0027_update_formation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Référentiel – Formation (cycle)',
                'verbose_name_plural': 'Référentiel – Formations (cycles)',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='RefModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255, unique=True)),
                ('volume_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Référentiel – Module',
                'verbose_name_plural': 'Référentiel – Modules',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='RefSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Référentiel – Site',
                'verbose_name_plural': 'Référentiel – Sites',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='RefBatiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batiments', to='formations.refsite')),
            ],
            options={
                'verbose_name': 'Référentiel – Bâtiment',
                'verbose_name_plural': 'Référentiel – Bâtiments',
                'ordering': ['nom'],
                'unique_together': {('site', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='RefSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('batiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salles', to='formations.refbatiment')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='formations.refsite')),
            ],
            options={
                'verbose_name': 'Référentiel – Salle',
                'verbose_name_plural': 'Référentiel – Salles',
                'ordering': ['nom'],
                'unique_together': {('site', 'batiment', 'nom')},
            },
        ),
    ]
