# Generated by Django 5.1.4 on 2026-04-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0028_add_referentiels'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(blank=True, default='', max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Référentiel – Catégorie',
                'verbose_name_plural': 'Référentiel – Catégories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RefGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(blank=True, default='', max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='formations.refcategorie')),
            ],
            options={
                'verbose_name': 'Référentiel – Grade',
                'verbose_name_plural': 'Référentiel – Grades',
                'ordering': ['code'],
            },
        ),
    ]
