# Generated by Django 5.1.4 on 2026-04-13 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0030_rename_participant_numero_to_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='refmodule',
            name='formation',
            field=models.ForeignKey(blank=True, help_text='Formation (cycle) auquel appartient ce module', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='formations.refformation'),
        ),
        migrations.AlterField(
            model_name='refmodule',
            name='intitule',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='refmodule',
            unique_together={('formation', 'intitule')},
        ),
    ]
