# Generated by Django 5.1.4 on 2026-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0034_formation_categorie_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='module',
            field=models.CharField(help_text='Cours', max_length=255),
        ),
    ]
