# Generated by Django 5.1.4 on 2026-04-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0037_migrate_module_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='module',
        ),
    ]
