# Generated by Django 5.1.4 on 2026-04-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0039_add_vague_to_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='numero',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='matricule',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
