# Generated by Django 5.1.4 on 2026-04-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0041_module_add_site_salle_dates_statut_formateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='batiment',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='duree_prevue_heures',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='site',
        ),
    ]
