# Generated by Django 5.1.4 on 2026-04-15 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0042_formation_remove_site_salle_duree'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrit_le', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_participants', to='formations.module')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_inscrits', to='formations.participant')),
            ],
            options={
                'verbose_name': 'Inscription module',
                'verbose_name_plural': 'Inscriptions modules',
                'unique_together': {('module', 'participant')},
            },
        ),
        migrations.DeleteModel(
            name='FormationParticipant',
        ),
    ]
