# Generated by Django 5.1.4 on 2026-04-15 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0045_remove_formation_fk_from_sessionformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrtoken',
            name='formation',
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='session',
            field=models.ForeignKey(default=8, help_text='Séance liée à ce QR code', on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='formations.sessionformation'),
            preserve_default=False,
        ),
    ]
