# Generated by Django 5.1.4 on 2026-04-16 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0048_rename_sessionformation_sessionmodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={},
        ),
        migrations.RemoveField(
            model_name='formation',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='creee_par',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='groupe',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='secretariat',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='session_demarree_le',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='session_terminee_le',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='superviseur',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='superviseur_assigne_le',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='vague',
        ),
        migrations.AddField(
            model_name='module',
            name='creee_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant créé le module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='superviseur',
            field=models.ForeignKey(blank=True, help_text='Encadrant responsable du module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules_supervises', to=settings.AUTH_USER_MODEL),
        ),
    ]
