# Generated by Django 5.1.4 on 2026-04-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0049_module_add_superviseur_creee_par'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
    ]
