# Generated by Django 5.1.4 on 2026-04-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0050_module_remove_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefTypeSecretariat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(blank=True, default='', max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Référentiel \u2013 Type de secrétariat',
                'verbose_name_plural': 'Référentiel \u2013 Types de secrétariat',
                'ordering': ['code'],
            },
        ),
        # Insérer les types existants A/B/C dans le référentiel
        migrations.RunPython(
            lambda apps, schema_editor: [
                apps.get_model('formations', 'RefTypeSecretariat').objects.get_or_create(
                    code=code, defaults={'libelle': libelle}
                )
                for code, libelle in [('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C')]
            ],
            reverse_code=migrations.RunPython.noop,
        ),
        # Rendre le champ varchar nullable avant de le vider
        migrations.RunSQL(
            "ALTER TABLE formations_secretariat ALTER COLUMN type DROP NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Vider le champ type (varchar) avant conversion en FK
        migrations.RunSQL(
            "UPDATE formations_secretariat SET type = NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='secretariat',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Type de secrétariat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretariats', to='formations.reftypesecretariat'),
        ),
    ]
