# Generated by Django 5.1.4 on 2026-04-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0051_ref_type_secretariat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reftypesecretariat',
            options={'ordering': ['libelle'], 'verbose_name': 'Référentiel – Type de secrétariat', 'verbose_name_plural': 'Référentiel – Types de secrétariat'},
        ),
        migrations.RemoveField(
            model_name='reftypesecretariat',
            name='code',
        ),
        migrations.AlterField(
            model_name='reftypesecretariat',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
