# Generated by Django 5.1.4 on 2026-04-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0052_ref_type_secretariat_no_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refcategorie',
            options={'ordering': ['libelle'], 'verbose_name': 'Référentiel – Catégorie', 'verbose_name_plural': 'Référentiel – Catégories'},
        ),
        migrations.AlterModelOptions(
            name='refgrade',
            options={'ordering': ['libelle'], 'verbose_name': 'Référentiel – Grade', 'verbose_name_plural': 'Référentiel – Grades'},
        ),
        migrations.RemoveField(
            model_name='refcategorie',
            name='code',
        ),
        migrations.AlterUniqueTogether(
            name='refgrade',
            unique_together={('categorie', 'libelle')},
        ),
        migrations.AlterField(
            model_name='refcategorie',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='refgrade',
            name='libelle',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='refgrade',
            name='code',
        ),
    ]
