# Generated by Django 5.1.4 on 2026-05-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0059_module_cycle_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='batiment',
            field=models.CharField(blank=True, default='', help_text='Bâtiment ou zone (import Excel : colonne « Bâtiment »).', max_length=255, verbose_name='Bâtiment'),
        ),
        migrations.AlterField(
            model_name='module',
            name='salle',
            field=models.CharField(blank=True, default='', help_text='Salle ou lieu précis (import Excel : colonne « Salle »).', max_length=100, verbose_name='Salle'),
        ),
        migrations.AlterField(
            model_name='module',
            name='site',
            field=models.CharField(blank=True, default='', help_text='Centre de formation (import : colonne « Site » ; aligné RefSite pour la géolocalisation mobile).', max_length=255, verbose_name='Site'),
        ),
    ]
