# Generated by Django 5.1.4 on 2026-05-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0061_module_site_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Centre de formation (référentiel). Sert à la géolocalisation mobile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='formations.refsite', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='module',
            name='site_legacy',
            field=models.CharField(blank=True, default='', help_text='Ancien champ texte. Utiliser le champ FK « site » (RefSite) à la place.', max_length=255, verbose_name='Site (legacy)'),
        ),
    ]
