# Generated by Django 5.1.4 on 2026-06-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0066_formateur_piece_identite_compte_bancaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['formation'], 'verbose_name': 'Formation', 'verbose_name_plural': 'Formations'},
        ),
        migrations.AlterModelOptions(
            name='qrtoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Code QR', 'verbose_name_plural': 'Codes QR'},
        ),
        migrations.AlterModelOptions(
            name='sessionmodule',
            options={'ordering': ['date_journee', 'heure_debut_prevue', 'numero'], 'verbose_name': 'Séance', 'verbose_name_plural': 'Séances'},
        ),
    ]
