# Generated by Django 5.1.4 on 2026-06-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0075_financesettings_export_pied_page'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('formation', 'intitule', 'grade', 'groupe', 'vague')},
        ),
    ]
