# Generated by Django 5.1.4 on 2026-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0081_refmodule_volume_formation_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='observations',
            field=models.TextField(blank=True, default='', help_text='Notes / observations libres sur le formateur (consultables par les archives).', verbose_name='Observations'),
        ),
    ]
