# Generated by Django 5.1.4 on 2026-09-15 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0003_departement_adjoint_departement_email_and_more'),
        ('formations', '0092_refsalle_sqlite_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secretariat',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secretariat',
            name='adjoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretariats_adjoint', to=settings.AUTH_USER_MODEL, verbose_name='Adjoint(e)'),
        ),
        migrations.AddField(
            model_name='secretariat',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretariats', to='administrations.departement', verbose_name='Département de rattachement'),
        ),
        migrations.AddField(
            model_name='secretariat',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretariats', to='administrations.direction', verbose_name='Direction de rattachement'),
        ),
        migrations.AddField(
            model_name='secretariat',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='secretariat',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Localisation'),
        ),
        migrations.AddField(
            model_name='secretariat',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddConstraint(
            model_name='secretariat',
            constraint=models.CheckConstraint(condition=models.Q(('direction__isnull', True), ('departement__isnull', True), _connector='OR'), name='secretariat_rattache_au_plus_un'),
        ),
    ]
