# Generated by Django 5.1.4 on 2026-09-15 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edts', '0002_affectationcreneau_formateur_and_more'),
        ('formations', '0093_secretariat_actif_secretariat_adjoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='seance_edt',
            field=models.ForeignKey(blank=True, help_text="Séance LMD (créneau d'emploi du temps) liée à ce QR code", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='edts.affectationcreneau'),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Séance liée à ce QR code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='formations.sessionmodule'),
        ),
    ]
