# Generated by Django 5.1.4 on 2026-09-15 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0094_qrtoken_seance_edt_alter_qrtoken_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='ref_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.refformation', verbose_name='Cycle de référence'),
        ),
        migrations.AddField(
            model_name='refformation',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Code court du cycle (ex. LIC-ADMIN).', max_length=30),
        ),
        migrations.AddField(
            model_name='refformation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='refformation',
            name='domaine',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='refformation',
            name='duree_annees',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Durée (années)'),
        ),
        migrations.AddField(
            model_name='refformation',
            name='mention',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='refformation',
            name='nb_credites',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Crédits ECTS visés'),
        ),
        migrations.AddField(
            model_name='refformation',
            name='nb_semestres',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de semestres'),
        ),
        migrations.AddField(
            model_name='refformation',
            name='type_diplome',
            field=models.CharField(blank=True, choices=[('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('DUT', 'DUT / BTS'), ('PROFESSIONNALISANT', 'Cycle professionnalisant'), ('AUTRE', 'Autre')], default='', max_length=20, verbose_name='Type de diplôme'),
        ),
    ]
