# Generated by Django 5.1.4 on 2026-09-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0095_formation_ref_formation_refformation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refformation',
            name='filiere_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text="L6 : code stable de la filière métier (F01…F08) — voir docs/audits/A-4.5 §2. Vide si la ligne n'est rattachée à aucune filière validée.", max_length=10),
        ),
        migrations.AddField(
            model_name='refformation',
            name='perimetre',
            field=models.CharField(choices=[('INJS', 'INJS validé'), ('LEGACY', 'Legacy / autre source'), ('NON_DETERMINE', 'Non déterminé')], db_index=True, default='NON_DETERMINE', help_text='L6 : INJS = filière validée par la source métier ; LEGACY = corpus étranger (CPFAE/Sygepcpfae) exclu du référentiel INJS.', max_length=20),
        ),
        migrations.AddField(
            model_name='refformation',
            name='source',
            field=models.CharField(blank=True, default='', help_text='L6 : référence de la source métier ayant attesté la ligne.', max_length=100),
        ),
    ]
