# Generated by Django 5.1.4 on 2026-09-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0096_l6_referentiel_injs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refsalle',
            name='type_lieu',
            field=models.CharField(choices=[('SALLE', 'Salle'), ('AMPHI', 'Amphithéâtre'), ('GYMNASE', 'Gymnase'), ('REUNION', 'Salle de réunion'), ('CONFERENCE', 'Salle de conférence'), ('COURS', 'Salle de cours'), ('TD', 'Salle de TD'), ('TP', 'Salle de travaux pratiques'), ('INFORMATIQUE', 'Salle informatique'), ('LABORATOIRE', 'Laboratoire'), ('SPORT', 'Espace sportif couvert')], default='SALLE', max_length=20),
        ),
    ]
