# Generated by Django 5.2.16 on 2026-07-09 14:33

import django.db.models.deletion
from django.db import migrations, models


def sync_permissions(apps, schema_editor):
    from apps.accounts.rbac import sync_module_permissions
    sync_module_permissions()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Niveau 0 - Super Admin'), (1, 'Niveau 1 - Direction'), (2, 'Niveau 2 - Responsables'), (3, 'Niveau 3 - Pédagogique'), (4, 'Niveau 4 - Étudiant')], db_index=True, default=4)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['level', 'group__name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermissionRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Registre permissions INJS',
                'verbose_name_plural': 'Registre permissions INJS',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profiles', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RunPython(sync_permissions, migrations.RunPython.noop),
    ]
