# Generated by Django 5.1.4 on 2026-09-09 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0091_lot1_notes_workflow'),
        ('scolarite', '0014_alter_journalscolarite_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], db_index=True, max_length=10)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_prevue_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Durée calculée (laisser None pour auto-calcul).', null=True)),
            ],
            options={
                'verbose_name': 'LMD – Créneau type',
                'verbose_name_plural': 'LMD – Créneaux types',
                'ordering': ['jour', 'heure_debut'],
                'indexes': [models.Index(fields=['jour', 'heure_debut', 'heure_fin'], name='edts_crenea_jour_2c95c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_type', models.CharField(choices=[('FORMATION', 'Formation'), ('GROUPE', 'Groupe'), ('ENSEIGNANT', 'Enseignant'), ('SALLE', 'Salle')], db_index=True, max_length=15)),
                ('population_id', models.PositiveIntegerField(db_index=True, help_text='ID de la formation/groupe/enseignant/salle cible.')),
                ('population_denominateur', models.CharField(blank=True, default='', help_text='Libellé humain pour affichage et recherche.', max_length=255)),
                ('titre', models.CharField(blank=True, default='', max_length=255)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], db_index=True, default='BROUILLON', max_length=15)),
                ('rentree', models.DateField(blank=True, help_text='Date de rentrée pédagogique de cet EDT.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emplois_du_temps', to='scolarite.anneeacademique')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edt_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Emploi du temps',
                'verbose_name_plural': 'LMD – Emplois du temps',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflitCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conflit', models.CharField(choices=[('HORAIRE_ENSEIGNANT', 'Chevauchement enseignant'), ('HORAIRE_GROUPETUDIANT', 'Chevauchement groupe/étudiant'), ('HORAIRE_SALLE', 'Chevauchement salle'), ('HORAIRE_MODULE', 'Chevauchement module'), ('MANUEL', 'Signalé manuellement')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('lignes_creneaux', models.JSONField(default=list, help_text='Liste des identifiants ou représentations brutes des affectations en conflit.')),
                ('recalcule_le', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signale_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edt_conflits_signales', to=settings.AUTH_USER_MODEL)),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits', to='edts.emploidutemps')),
            ],
            options={
                'verbose_name': 'LMD – Conflit créneau',
                'verbose_name_plural': 'LMD – Conflits créneaux',
                'ordering': ['-recalcule_le'],
            },
        ),
        migrations.CreateModel(
            name='AffectationCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_debut', models.PositiveSmallIntegerField(db_index=True, help_text='Numéro de semaine académique de début (1-based).')),
                ('semaine_fin', models.PositiveSmallIntegerField(db_index=True, help_text='Numéro de semaine académique de fin.')),
                ('salle_nom', models.CharField(blank=True, default='', help_text='Salle attendue (chaîne éditable).', max_length=255)),
                ('enseignant_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='ID utilisateur enseignant/encadrant.', null=True)),
                ('enseignant_nom', models.CharField(blank=True, default='', help_text='Nom complet enseignant (dénormalisé pour recherche/planification).', max_length=255)),
                ('nature', models.CharField(choices=[('COURS', 'Cours'), ('TD', 'Travaux dirigés'), ('TP', 'Travaux pratiques'), ('EVALUATION', 'Évaluation'), ('REMPLACEMENT', 'Remplacement'), ('AUTRE', 'Autre')], default='COURS', max_length=15)),
                ('intitule', models.CharField(blank=True, default='', max_length=255)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edt_affectations_crees', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edt_affectations', to='formations.refformation')),
                ('groupe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edt_affectations', to='scolarite.groupe')),
                ('creneau_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='edts.creneautemplate')),
                ('emploi_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='edts.emploidutemps')),
            ],
            options={
                'verbose_name': 'LMD – Affectation créneau',
                'verbose_name_plural': 'LMD – Affectations créneaux',
                'ordering': ['emploi_du_temps', 'creneau_template__jour', 'creneau_template__heure_debut', 'semaine_debut'],
            },
        ),
        migrations.AddIndex(
            model_name='emploidutemps',
            index=models.Index(fields=['annee_academique', 'population_type', 'population_id'], name='edts_emploi_annee_a_13fbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='emploidutemps',
            index=models.Index(fields=['statut'], name='edts_emploi_statut_3d1a5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emploidutemps',
            unique_together={('annee_academique', 'population_type', 'population_id')},
        ),
        migrations.AddIndex(
            model_name='conflitcreneau',
            index=models.Index(fields=['emploi_du_temps', 'type_conflit'], name='edts_confli_emploi__ae2072_idx'),
        ),
        migrations.AddIndex(
            model_name='conflitcreneau',
            index=models.Index(fields=['actif', 'recalcule_le'], name='edts_confli_actif_c4620b_idx'),
        ),
        migrations.AddIndex(
            model_name='affectationcreneau',
            index=models.Index(fields=['emploi_du_temps', 'creneau_template', 'semaine_debut', 'semaine_fin'], name='edts__edt_creneau_semaine_idx'),
        ),
    ]
