# Generated by Django 5.1.4 on 2026-06-14 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0071_financeajustement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.TextField(help_text='Libellé de la question')),
                ('type_question', models.CharField(choices=[('NOTE', 'Note (1 à 5)'), ('CHOIX_UN', 'Choix unique'), ('CHOIX_MUL', 'Choix multiple'), ('TEXTE', 'Texte libre')], default='NOTE', max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('obligatoire', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['questionnaire', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ChoixQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='suiviEvaluation.question')),
            ],
            options={
                'verbose_name': 'Choix de réponse',
                'verbose_name_plural': 'Choix de réponse',
                'ordering': ['question', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('cible', models.CharField(choices=[('COURS', 'Évaluation du cours'), ('FORMATEUR', 'Évaluation du formateur')], help_text='Ce questionnaire évalue le cours ou le formateur ?', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('FERME', 'Fermé')], default='BROUILLON', max_length=20)),
                ('categorie', models.CharField(blank=True, default='', help_text='Catégorie de grade ciblée (A, B, C, D…). Vide = toutes catégories.', max_length=10)),
                ('date_ouverture', models.DateTimeField(blank=True, help_text="Date/heure d'ouverture aux auditeurs", null=True)),
                ('date_fermeture', models.DateTimeField(blank=True, help_text='Date/heure de fermeture automatique', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires_crees', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, help_text="Module concerné (laisser vide pour cibler tous les modules d'une catégorie)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='formations.module')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='suiviEvaluation.questionnaire'),
        ),
        migrations.CreateModel(
            name='ReponseQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soumis_le', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_soumises', to='formations.participant')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='suiviEvaluation.questionnaire')),
            ],
            options={
                'verbose_name': 'Soumission',
                'verbose_name_plural': 'Soumissions',
                'ordering': ['-soumis_le'],
                'unique_together': {('questionnaire', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('texte', models.TextField(blank=True, default='')),
                ('choix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_choix_unique', to='suiviEvaluation.choixquestion')),
                ('choix_multiples', models.ManyToManyField(blank=True, related_name='reponses_choix_multiple', to='suiviEvaluation.choixquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='suiviEvaluation.question')),
                ('soumission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_questions', to='suiviEvaluation.reponsequestionnaire')),
            ],
            options={
                'verbose_name': 'Réponse à une question',
                'verbose_name_plural': 'Réponses aux questions',
                'unique_together': {('soumission', 'question')},
            },
        ),
    ]
