# Generated by Django 5.1.4 on 2026-06-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suiviEvaluation', '0002_questionnaire_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='titre',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Liste des catégories ciblées (A, B, C, D…). Vide = toutes.'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='grades',
            field=models.JSONField(blank=True, default=list, help_text='Liste des grades ciblés (A3, A4, B1…). Vide = tous.'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='titres',
            field=models.JSONField(default=list, help_text='Liste des intitulés de modules ciblés (depuis le référentiel).'),
        ),
    ]
