# Generated by Django 5.2.15 on 2026-07-04 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='academics.institution'),
        ),
        migrations.AddField(
            model_name='program',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='academics.program'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='academics.program'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='teachingunit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_units', to='academics.department'),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='teaching_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_links', to='academics.teachingunit'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.teachingunit'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institution', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('institution', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('program', 'teaching_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('teaching_unit', 'code')},
        ),
    ]
