# Generated by Django 5.2.16 on 2026-07-09 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('track', models.CharField(choices=[('PL', 'Professeur de Lycée'), ('PC', 'Professeur de Collège'), ('BOTH', 'Lycée et Collège')], default='BOTH', max_length=5)),
                ('is_tronc_commun', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='track',
            field=models.CharField(blank=True, choices=[('PL', 'Professeur de Lycée'), ('PC', 'Professeur de Collège'), ('', 'Général')], default='', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programcourse',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_courses', to='academics.specialization'),
        ),
        migrations.AlterUniqueTogether(
            name='programcourse',
            unique_together={('program', 'teaching_unit', 'specialization')},
        ),
    ]
