# Generated by Django 5.2.16 on 2026-07-09 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_maquette_staps2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='StapsJobNomenclature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree_type', models.CharField(choices=[('L', 'Licence'), ('M', 'Master'), ('D', 'Doctorat'), ('DU', 'Diplôme Universitaire')], max_length=2)),
                ('civil_service_grade', models.CharField(choices=[('A3', 'Grade A3 — Professeur de Collège'), ('A4', 'Grade A4 — Professeur de Lycée')], db_index=True, max_length=2)),
                ('track', models.CharField(choices=[('PC', 'Professeur de Collège'), ('PL', 'Professeur de Lycée')], db_index=True, max_length=2)),
                ('job_title', models.CharField(max_length=255)),
                ('duration_years', models.PositiveSmallIntegerField(default=3)),
                ('competencies', models.TextField(blank=True)),
                ('career_outcomes', models.TextField(blank=True)),
                ('diploma_code', models.CharField(choices=[('CAPS', 'CAPS'), ('CAPEPS', 'CAPEPS'), ('CAPCS', 'CAPCS'), ('CAPCEPS', 'CAPCEPS')], db_index=True, max_length=10)),
                ('diploma_label', models.CharField(max_length=255)),
                ('employers', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_nomenclatures', to='academics.specialization')),
            ],
            options={
                'verbose_name': 'Nomenclature emploi STAPS',
                'verbose_name_plural': 'Nomenclature emplois STAPS',
                'ordering': ['degree_type', 'specialization__code'],
                'unique_together': {('degree_type', 'specialization')},
            },
        ),
    ]
