# Generated by Django 5.2.16 on 2026-07-22 16:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_nomenclature_emplois_staps'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text="Seuil de validation de l'ECUE (/20)", max_digits=5, verbose_name='Note de validation'),
        ),
        migrations.AddField(
            model_name='teachingunit',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Seuil de validation ECUE/UE (/20)', max_digits=5, verbose_name='Note de validation'),
        ),
    ]
