# Generated by Django 5.2.16 on 2026-08-21 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_course_ue_passing_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('weekly_rhythm', models.CharField(choices=[('full', 'Toutes les semaines'), ('w1', '1re semaine du mois'), ('w1_2', '2 premières semaines du mois'), ('w1_3', '3 premières semaines du mois')], default='full', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_periods', to='academics.academicyear')),
                ('program', models.ForeignKey(blank=True, help_text='Vide = période commune à toutes les filières.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation_periods', to='academics.program')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formation_periods', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Période de formation',
                'verbose_name_plural': 'Périodes de formation',
                'ordering': ['academic_year', 'order', 'start_date'],
                'unique_together': {('academic_year', 'program', 'label')},
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('label', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='academics.institution')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['-date'],
                'unique_together': {('institution', 'date')},
            },
        ),
    ]
