# Generated by Django 5.1.4 on 2026-09-08 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=150)),
                ('grade', models.CharField(blank=True, default='', max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'LMD – Fonction',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LMD – Service',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('type_contrat', models.CharField(choices=[('CONTRAT', 'Contractuel'), ('VACATAIRE', 'Vacataire'), ('FONCTIONNAIRE', 'Fonctionnaire'), ('BENEVOLE', 'Bénévole')], default='CONTRAT', max_length=20)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_rh', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LMD – Agent',
                'verbose_name_plural': 'LMD – Agents',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='DisponibiliteAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_indispo', models.CharField(choices=[('CONGE', 'Congé'), ('MISSION', 'Mission'), ('FORMATION', 'Formation'), ('MALADIE', 'Maladie'), ('AUTRE', 'Autre')], default='CONGE', max_length=15)),
                ('motif', models.CharField(blank=True, default='', max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='ressources_humaines.agent')),
            ],
            options={
                'verbose_name': 'LMD – Disponibilité agent',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CONTRAT', 'Contrat'), ('AVIS', 'Avis de situation'), ('EVALUATION', 'Évaluation'), ('ATTESTATION', 'Attestation'), ('AUTRE', 'Autre')], default='CONTRAT', max_length=15)),
                ('intitule', models.CharField(max_length=255)),
                ('fichier', models.FileField(blank=True, upload_to='rh/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ressources_humaines.agent')),
            ],
            options={
                'verbose_name': 'LMD – Document RH',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffectationRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='ressources_humaines.agent')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='ressources_humaines.fonction')),
            ],
            options={
                'verbose_name': 'LMD – Affectation RH',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='fonction',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fonctions', to='ressources_humaines.service'),
        ),
        migrations.AlterUniqueTogether(
            name='fonction',
            unique_together={('intitule', 'service')},
        ),
    ]
