# Generated by Django 5.1.4 on 2026-09-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0002_direction_departement'),
        ('ressources_humaines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='departement',
            field=models.ForeignKey(blank=True, help_text='Département de rattachement (nullable : service non rattaché).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='administrations.departement'),
        ),
    ]
