# Generated by Django 5.1.4 on 2026-09-15 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources_humaines', '0002_service_departement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='adjoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_adjointes', to=settings.AUTH_USER_MODEL, verbose_name='Adjoint(e)'),
        ),
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Code court du service (ex. SCOL01).', max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='service',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Localisation (bâtiment, étage, porte)'),
        ),
        migrations.AddField(
            model_name='service',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_pilotes', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='service',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone'),
        ),
    ]
