# Generated by Django 5.1.4 on 2026-09-15 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources_humaines', '0003_service_adjoint_service_code_service_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Pour les sous-unités (bureau, unité, cellule) d’un service.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sous_unites', to='ressources_humaines.service', verbose_name='Unité rattachante'),
        ),
        migrations.AddField(
            model_name='service',
            name='type_unite',
            field=models.CharField(choices=[('SERVICE', 'Service'), ('BUREAU', 'Bureau'), ('UNITE', 'Unité'), ('CELLULE', 'Cellule'), ('AUTRE', 'Autre')], default='SERVICE', max_length=12, verbose_name='Type d’unité'),
        ),
    ]
