# Generated by Django 5.1.4 on 2026-09-21 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('DEPARTEMENT', 'Departement'), ('SERVICE', 'Service')], default='DEPARTEMENT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_resp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departement/Service',
                'verbose_name_plural': 'Departements/Services',
                'ordering': ['nom'],
            },
        ),
    ]
