# Generated by Django 5.2.15 on 2026-07-04 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(db_index=True, max_length=20, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(default='Ivoirienne', max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='students/qr/')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('graduated', 'Diplômé'), ('withdrawn', 'Retiré')], db_index=True, default='active', max_length=20)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.program')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.promotion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_type', models.CharField(choices=[('administrative', 'Inscription administrative'), ('pedagogical', 'Inscription pédagogique'), ('pre_registration', 'Préinscription')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], db_index=True, default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicyear')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_enrollments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester_average', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('credits_acquired', models.PositiveSmallIntegerField(default=0)),
                ('credits_total', models.PositiveSmallIntegerField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('decision', models.CharField(blank=True, max_length=50)),
                ('snapshot_data', models.JSONField(default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program', 'promotion', 'status'], name='students_st_program_4a342b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'academic_year', 'enrollment_type')},
        ),
        migrations.AddIndex(
            model_name='academicrecord',
            index=models.Index(fields=['student', 'academic_year'], name='students_ac_student_3d75d1_idx'),
        ),
    ]
