# Generated by Django 5.1.4 on 2026-09-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0002_triggers_immuabilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemetier',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions canoniques octroyées par ce rôle (matrice U3).', related_name='roles_octroyants', to='habilitations.permissionmetier'),
        ),
    ]
