# Generated by Django 5.1.4 on 2026-09-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0003_rolemetier_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmetier',
            name='action',
            field=models.CharField(choices=[('consulter', 'Consulter'), ('creer', 'Créer'), ('modifier', 'Modifier'), ('soumettre', 'Soumettre'), ('valider', 'Valider'), ('rejeter', 'Rejeter'), ('publier', 'Publier'), ('annuler', 'Annuler'), ('exporter', 'Exporter'), ('imprimer', 'Imprimer'), ('archiver', 'Archiver'), ('supprimer', 'Supprimer'), ('administrer', 'Administrer'), ('saisir', 'Saisir'), ('verrouiller', 'Verrouiller'), ('calculer', 'Calculer'), ('signer', 'Signer'), ('generer', 'Générer'), ('editer', 'Éditer'), ('revoquer', 'Révoquer'), ('deposer', 'Déposer'), ('instruire', 'Instruire'), ('decider', 'Décider'), ('ouvrir', 'Ouvrir'), ('cloturer', 'Clôturer'), ('forcer', 'Forcer'), ('certifier', 'Certifier'), ('deplacer', 'Déplacer'), ('remplacer', 'Remplacer'), ('resoudre', 'Résoudre'), ('configurer', 'Configurer')], max_length=20),
        ),
    ]
