# Generated by Django 5.1.4 on 2026-09-14 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0005_charger_referentiel_injs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attributionrole',
            name='notification_echeance_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compteutilisateur',
            name='date_preavis_inactivite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compteutilisateur',
            name='exempt_inactivite',
            field=models.BooleanField(default=False, help_text='Exempte le compte de la suspension pour inactivité (congé longue durée…).'),
        ),
        migrations.AddField(
            model_name='delegationhabilitation',
            name='notification_echeance_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalhabilitation',
            name='delegation_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journalisees', to='habilitations.delegationhabilitation'),
        ),
        migrations.AddField(
            model_name='permissionattribuee',
            name='notification_echeance_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politiquesecurite',
            name='delai_grace_fin_relation_jours',
            field=models.PositiveIntegerField(default=7, help_text='Délai de grâce après une fin de relation avant toute proposition.'),
        ),
        migrations.AddField(
            model_name='politiquesecurite',
            name='echeance_notification_jours',
            field=models.PositiveIntegerField(default=7, help_text="Anticipation (jours) de la notification d'échéance des attributions."),
        ),
        migrations.AddField(
            model_name='politiquesecurite',
            name='plafond_quotidien_propositions',
            field=models.PositiveIntegerField(default=50, help_text='Au-delà, les propositions excédentaires sont bloquées et une alerte est émise.'),
        ),
        migrations.AddField(
            model_name='politiquesecurite',
            name='preavis_suspension_jours',
            field=models.PositiveIntegerField(default=15, help_text="Préavis notifié avant la proposition de suspension d'inactivité."),
        ),
        migrations.AlterField(
            model_name='journalhabilitation',
            name='type_evenement',
            field=models.CharField(choices=[('COMPTE_CREE', 'Création de compte'), ('COMPTE_ACTIVE', 'Activation de compte'), ('COMPTE_SUSPENDU', 'Suspension de compte'), ('COMPTE_DESACTIVE', 'Désactivation de compte'), ('COMPTE_VERROUILLE', 'Verrouillage de compte'), ('COMPTE_DEVERROUILLE', 'Déverrouillage de compte'), ('COMPTE_EXPIRE', 'Expiration de compte'), ('MOT_DE_PASSE_REINITIALISE', 'Réinitialisation de mot de passe'), ('ROLE_ATTRIBUE', 'Attribution de rôle'), ('ROLE_REVOQUE', 'Révocation de rôle'), ('PERMISSION_OCTROYEE', 'Octroi de permission'), ('PERMISSION_RETIREE', 'Retrait de permission'), ('DELEGATION_CREE', 'Création de délégation'), ('DELEGATION_REVOQUEE', 'Révocation de délégation'), ('POLITIQUE_MODIFIEE', 'Modification de politique'), ('CONNEXION', 'Connexion'), ('CONNEXION_ECHOUEE', 'Échec de connexion'), ('DECONNEXION', 'Déconnexion'), ('SESSION_REVOQUEE', 'Révocation de session'), ('APPAREIL_REVOQUE', 'Révocation d’appareil'), ('ACCES_REFUSE', 'Accès refusé sur ressource sensible'), ('AUTO_ELEVATION_TENTEE', 'Tentative d’auto-élévation'), ('TRANSITION_REFUSEE', 'Transition de statut refusée'), ('PROPOSITION_DEPOSEE', 'Proposition de provisionnement déposée'), ('PROPOSITION_APPROUVEE', 'Proposition approuvée'), ('PROPOSITION_REJETEE', 'Proposition rejetée'), ('IMPORT_EXECUTE', 'Exécution d’import en masse'), ('IMPORTA_ANNULE', 'Annulation d’import en masse'), ('EXPIRATION_AUTO', 'Expiration automatique à terme'), ('DELEGATION_ACTIVEE', 'Activation de délégation'), ('ACTION_DELEGUEE', 'Action exercée par délégation'), ('AUTRE', 'Autre événement')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ExecutionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ECHEC', 'Échec (aucune écriture)'), ('ANNULE', 'Annulé (comptes désactivés)')], db_index=True, default='EN_COURS', max_length=10)),
                ('nom_fichier', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.PositiveIntegerField(default=0)),
                ('crees', models.PositiveIntegerField(default=0)),
                ('erreurs', models.PositiveIntegerField(default=0)),
                ('rapport', models.JSONField(blank=True, default=dict)),
                ('rapport_annulation', models.JSONField(blank=True, default=dict)),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.TextField(blank=True, default='')),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_annules', to=settings.AUTH_USER_MODEL)),
                ('lance_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_lances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exécution d’import en masse',
                'verbose_name_plural': 'Exécutions d’import en masse',
                'ordering': ('-date_execution',),
            },
        ),
        migrations.AddField(
            model_name='compteutilisateur',
            name='import_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_crees', to='habilitations.executionimport'),
        ),
        migrations.CreateModel(
            name='NotificationHabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('PREAVIS_SUSPENSION', 'Préavis de suspension pour inactivité'), ('ECHEANCE_ATTRIBUTION', 'Échéance d’attribution'), ('ECHEANCE_DEROGATION', 'Échéance de dérogation'), ('ECHEANCE_DELEGATION', 'Échéance de délégation'), ('ALERTE_PLAFOND', 'Plafond quotidien de propositions atteint'), ('PROPOSITION', 'Proposition de provisionnement à instruire'), ('AUTRE', 'Autre notification')], db_index=True, max_length=24)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('metadonnees', models.JSONField(blank=True, default=dict)),
                ('lu', models.BooleanField(db_index=True, default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='habilitations.compteutilisateur')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_habilitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification d’habilitation',
                'verbose_name_plural': 'Notifications d’habilitation',
                'ordering': ('-date_creation',),
                'indexes': [models.Index(fields=['destinataire', 'lu'], name='habilitatio_destina_7c657b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropositionProvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declencheur', models.CharField(choices=[('ADMISSION', 'Admission d’un candidat validée'), ('INSCRIPTION', 'Inscription administrative validée'), ('RECRUTEMENT', 'Recrutement d’un agent enregistré en RH'), ('AFFECTATION_ENSEIGNANT', 'Affectation pédagogique d’un enseignant'), ('FIN_RELATION', 'Fin d’inscription, départ ou fin de contrat'), ('INACTIVITE', 'Compte inactif au-delà de la durée admise')], db_index=True, max_length=24)),
                ('action_proposee', models.CharField(choices=[('CREER_COMPTE', 'Créer un compte'), ('ACTIVER_COMPTE', 'Activer un compte'), ('ATTRIBUER_ROLE', 'Attribuer un rôle'), ('SUSPENDRE_COMPTE', 'Suspendre un compte'), ('DESACTIVER_COMPTE', 'Désactiver un compte')], max_length=20)),
                ('source_app', models.CharField(max_length=60)),
                ('source_modele', models.CharField(max_length=80)),
                ('source_objet_id', models.CharField(max_length=64)),
                ('source_libelle', models.CharField(blank=True, default='', max_length=255)),
                ('proposition', models.JSONField(blank=True, default=dict)),
                ('resultat', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('APPLIQUEE', 'Appliquée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=12)),
                ('cle_dedoublonnage', models.CharField(max_length=180, unique=True)),
                ('motif', models.TextField(blank=True, default='')),
                ('motif_rejet', models.TextField(blank=True, default='')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_approuvees', to=settings.AUTH_USER_MODEL)),
                ('compte_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions', to='habilitations.compteutilisateur')),
            ],
            options={
                'verbose_name': 'Proposition de provisionnement',
                'verbose_name_plural': 'Propositions de provisionnement',
                'ordering': ('-cree_le',),
                'indexes': [models.Index(fields=['declencheur', 'statut'], name='habilitatio_declenc_c7f2d3_idx'), models.Index(fields=['source_app', 'source_modele', 'source_objet_id'], name='habilitatio_source__c80444_idx')],
            },
        ),
    ]
