# Generated by Django 5.1.4 on 2026-09-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0006_attributionrole_notification_echeance_le_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhabilitation',
            name='categorie',
            field=models.CharField(choices=[('PREAVIS_SUSPENSION', 'Préavis de suspension pour inactivité'), ('ECHEANCE_ATTRIBUTION', 'Échéance d’attribution'), ('ECHEANCE_DEROGATION', 'Échéance de dérogation'), ('ECHEANCE_DELEGATION', 'Échéance de délégation'), ('ECHEANCE_COMPTE', 'Échéance du compte'), ('EXPIRATION_INVITATION', 'Invitation expirée'), ('ALERTE_PLAFOND', 'Plafond quotidien de propositions atteint'), ('PROPOSITION', 'Proposition de provisionnement à instruire'), ('AUTRE', 'Autre notification')], db_index=True, max_length=24),
        ),
    ]
