# Generated by Django 5.1.4 on 2026-09-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0007_alter_notificationhabilitation_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositionprovisionnement',
            name='declencheur',
            field=models.CharField(choices=[('ADMISSION', 'Admission d’un candidat validée'), ('INSCRIPTION', 'Inscription administrative validée'), ('RECRUTEMENT', 'Recrutement d’un agent enregistré en RH'), ('AFFECTATION_ENSEIGNANT', 'Affectation pédagogique d’un enseignant'), ('FIN_RELATION', 'Fin d’inscription, départ ou fin de contrat'), ('JURY', 'Désignation d’un membre de jury'), ('INACTIVITE', 'Compte inactif au-delà de la durée admise')], db_index=True, max_length=24),
        ),
    ]
