# Generated by Django 5.1.4 on 2026-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrations', '0002_direction_departement'),
        ('habilitations', '0008_alter_propositionprovisionnement_declencheur'),
        ('ressources_humaines', '0002_service_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='compteutilisateur',
            name='departements',
            field=models.ManyToManyField(blank=True, help_text='Départements dont le compte est rattaché.', related_name='comptes', to='administrations.departement'),
        ),
        migrations.AddField(
            model_name='compteutilisateur',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Services dont le compte est rattaché.', related_name='comptes', to='ressources_humaines.service'),
        ),
    ]
