# Generated by Django 5.1.4 on 2026-09-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0012_alter_journalhabilitation_type_evenement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perimetre',
            name='type',
            field=models.CharField(choices=[('INJS_ENTIER', 'INJS tout entière'), ('DIRECTION', 'Une direction'), ('DEPARTEMENT', 'Un département'), ('SERVICE', 'Un service administratif'), ('SECRETARIAT', 'Un secrétariat'), ('SITE', 'Un site physique'), ('FORMATION', 'Une formation'), ('PARCOURS', 'Un parcours'), ('NIVEAU', 'Un niveau (L1, L2…)'), ('GROUPE', 'Un groupe pédagogique'), ('MODULE_ECUE', 'Un module / une ECUE'), ('ETUDIANT', 'Un étudiant nommément désigné'), ('PROPRE_COMPTE', 'Son propre compte / dossier')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='permissionmetier',
            name='portee_maximale',
            field=models.CharField(choices=[('INJS_ENTIER', 'INJS tout entière'), ('DIRECTION', 'Une direction'), ('DEPARTEMENT', 'Un département'), ('SERVICE', 'Un service administratif'), ('SECRETARIAT', 'Un secrétariat'), ('SITE', 'Un site physique'), ('FORMATION', 'Une formation'), ('PARCOURS', 'Un parcours'), ('NIVEAU', 'Un niveau (L1, L2…)'), ('GROUPE', 'Un groupe pédagogique'), ('MODULE_ECUE', 'Un module / une ECUE'), ('ETUDIANT', 'Un étudiant nommément désigné'), ('PROPRE_COMPTE', 'Son propre compte / dossier')], default='INJS_ENTIER', help_text="Portée la plus large dans laquelle cette permission peut s'exercer.", max_length=20),
        ),
        migrations.AlterField(
            model_name='rolemetier',
            name='perimetre_defaut',
            field=models.CharField(choices=[('INJS_ENTIER', 'INJS tout entière'), ('DIRECTION', 'Une direction'), ('DEPARTEMENT', 'Un département'), ('SERVICE', 'Un service administratif'), ('SECRETARIAT', 'Un secrétariat'), ('SITE', 'Un site physique'), ('FORMATION', 'Une formation'), ('PARCOURS', 'Un parcours'), ('NIVEAU', 'Un niveau (L1, L2…)'), ('GROUPE', 'Un groupe pédagogique'), ('MODULE_ECUE', 'Un module / une ECUE'), ('ETUDIANT', 'Un étudiant nommément désigné'), ('PROPRE_COMPTE', 'Son propre compte / dossier')], default='INJS_ENTIER', max_length=20),
        ),
    ]
