# Generated by Django 5.1.4 on 2026-09-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0013_alter_perimetre_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalhabilitation',
            name='type_evenement',
            field=models.CharField(choices=[('COMPTE_CREE', 'Création de compte'), ('COMPTE_ACTIVE', 'Activation de compte'), ('COMPTE_SUSPENDU', 'Suspension de compte'), ('COMPTE_DESACTIVE', 'Désactivation de compte'), ('COMPTE_VERROUILLE', 'Verrouillage de compte'), ('COMPTE_DEVERROUILLE', 'Déverrouillage de compte'), ('COMPTE_EXPIRE', 'Expiration de compte'), ('MOT_DE_PASSE_REINITIALISE', 'Réinitialisation de mot de passe'), ('ROLE_ATTRIBUE', 'Attribution de rôle'), ('ROLE_REVOQUE', 'Révocation de rôle'), ('PERMISSION_OCTROYEE', 'Octroi de permission'), ('PERMISSION_RETIREE', 'Retrait de permission'), ('DELEGATION_CREE', 'Création de délégation'), ('DELEGATION_REVOQUEE', 'Révocation de délégation'), ('POLITIQUE_MODIFIEE', 'Modification de politique'), ('CONNEXION', 'Connexion'), ('CONNEXION_ECHOUEE', 'Échec de connexion'), ('CONNEXION_REFUSEE_VERROUILLEE', 'Connexion refusée : compte verrouillé'), ('MFA_ETAPSE_DEMANDEE', 'Étape MFA demandée à la connexion'), ('MFA_ACTIVE', 'Activation du MFA (TOTP)'), ('MFA_DESACTIVE', 'Désactivation du MFA (TOTP)'), ('DECONNEXION', 'Déconnexion'), ('SESSION_REVOQUEE', 'Révocation de session'), ('APPAREIL_REVOQUE', 'Révocation d’appareil'), ('ACCES_REFUSE', 'Accès refusé sur ressource sensible'), ('AUTO_ELEVATION_TENTEE', 'Tentative d’auto-élévation'), ('TRANSITION_REFUSEE', 'Transition de statut refusée'), ('PROPOSITION_DEPOSEE', 'Proposition de provisionnement déposée'), ('PROPOSITION_APPROUVEE', 'Proposition approuvée'), ('PROPOSITION_REJETEE', 'Proposition rejetée'), ('IMPORT_EXECUTE', 'Exécution d’import en masse'), ('IMPORTA_ANNULE', 'Annulation d’import en masse'), ('EXPIRATION_AUTO', 'Expiration automatique à terme'), ('DELEGATION_ACTIVEE', 'Activation de délégation'), ('ACTION_DELEGUEE', 'Action exercée par délégation'), ('ORGANISATION_MODIFIEE', 'Modification de l’organisation (direction, département, service, rattachement)'), ('ORGANISATION_CREEE', 'Création d’une unité d’organigramme'), ('ORGANISATION_DESACTIVEE', 'Désactivation d’une unité d’organigramme'), ('AUTRE', 'Autre événement')], db_index=True, max_length=40),
        ),
    ]
