# Generated by Django 5.1.4 on 2026-10-06 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0014_alter_journalhabilitation_type_evenement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalhabilitation',
            name='type_evenement',
            field=models.CharField(choices=[('COMPTE_CREE', 'Création de compte'), ('COMPTE_ACTIVE', 'Activation de compte'), ('COMPTE_SUSPENDU', 'Suspension de compte'), ('COMPTE_DESACTIVE', 'Désactivation de compte'), ('COMPTE_VERROUILLE', 'Verrouillage de compte'), ('COMPTE_DEVERROUILLE', 'Déverrouillage de compte'), ('COMPTE_EXPIRE', 'Expiration de compte'), ('MOT_DE_PASSE_REINITIALISE', 'Réinitialisation de mot de passe'), ('ROLE_ATTRIBUE', 'Attribution de rôle'), ('ROLE_REVOQUE', 'Révocation de rôle'), ('PERMISSION_OCTROYEE', 'Octroi de permission'), ('PERMISSION_RETIREE', 'Retrait de permission'), ('DELEGATION_CREE', 'Création de délégation'), ('DELEGATION_REVOQUEE', 'Révocation de délégation'), ('POLITIQUE_MODIFIEE', 'Modification de politique'), ('CONNEXION', 'Connexion'), ('CONNEXION_ECHOUEE', 'Échec de connexion'), ('CONNEXION_REFUSEE_VERROUILLEE', 'Connexion refusée : compte verrouillé'), ('MFA_ETAPSE_DEMANDEE', 'Étape MFA demandée à la connexion'), ('MFA_ACTIVE', 'Activation du MFA (TOTP)'), ('MFA_DESACTIVE', 'Désactivation du MFA (TOTP)'), ('DECONNEXION', 'Déconnexion'), ('SESSION_REVOQUEE', 'Révocation de session'), ('APPAREIL_REVOQUE', 'Révocation d’appareil'), ('ACCES_REFUSE', 'Accès refusé sur ressource sensible'), ('AUTO_ELEVATION_TENTEE', 'Tentative d’auto-élévation'), ('TRANSITION_REFUSEE', 'Transition de statut refusée'), ('PROPOSITION_DEPOSEE', 'Proposition de provisionnement déposée'), ('PROPOSITION_APPROUVEE', 'Proposition approuvée'), ('PROPOSITION_REJETEE', 'Proposition rejetée'), ('IMPORT_EXECUTE', 'Exécution d’import en masse'), ('IMPORTA_ANNULE', 'Annulation d’import en masse'), ('EXPIRATION_AUTO', 'Expiration automatique à terme'), ('DELEGATION_ACTIVEE', 'Activation de délégation'), ('ACTION_DELEGUEE', 'Action exercée par délégation'), ('ORGANISATION_MODIFIEE', 'Modification de l’organisation (direction, département, service, rattachement)'), ('ORGANISATION_CREEE', 'Création d’une unité d’organigramme'), ('ORGANISATION_DESACTIVEE', 'Désactivation d’une unité d’organigramme'), ('ROLE_VERSIONNE', 'Versionnement de rôle'), ('ROLE_RESTAURE', 'Restauration d’une version de rôle'), ('AUTRE', 'Autre événement')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='RoleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Numéro de version, croissant par rôle (1, 2, 3…).')),
                ('instant', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('motif', models.TextField(blank=True, default='', help_text='Motif de la capture ou de la restauration.')),
                ('source', models.CharField(choices=[('MANUEL', 'Capture manuelle'), ('AVANT_RESTAURATION', 'Capture automatique avant restauration'), ('RESTAURATION', 'État restauré')], default='MANUEL', max_length=20)),
                ('donnees', models.JSONField(help_text='Instantané : champs versionnés + codes des permissions et des rôles incompatibles au moment de la capture.')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_roles_creees', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='habilitations.rolemetier')),
            ],
            options={
                'verbose_name': 'Version de rôle métier',
                'verbose_name_plural': 'Versions des rôles métier',
                'ordering': ('role', '-numero'),
                'constraints': [models.UniqueConstraint(fields=('role', 'numero'), name='hab_roleversion_role_numero_unique')],
            },
        ),
    ]
