# Generated by Django 5.1.4 on 2026-10-06 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations', '0015_alter_journalhabilitation_type_evenement_roleversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalhabilitation',
            name='type_evenement',
            field=models.CharField(choices=[('COMPTE_CREE', 'Création de compte'), ('COMPTE_ACTIVE', 'Activation de compte'), ('COMPTE_SUSPENDU', 'Suspension de compte'), ('COMPTE_DESACTIVE', 'Désactivation de compte'), ('COMPTE_VERROUILLE', 'Verrouillage de compte'), ('COMPTE_DEVERROUILLE', 'Déverrouillage de compte'), ('COMPTE_EXPIRE', 'Expiration de compte'), ('MOT_DE_PASSE_REINITIALISE', 'Réinitialisation de mot de passe'), ('ROLE_ATTRIBUE', 'Attribution de rôle'), ('ROLE_REVOQUE', 'Révocation de rôle'), ('PERMISSION_OCTROYEE', 'Octroi de permission'), ('PERMISSION_RETIREE', 'Retrait de permission'), ('DELEGATION_CREE', 'Création de délégation'), ('DELEGATION_REVOQUEE', 'Révocation de délégation'), ('POLITIQUE_MODIFIEE', 'Modification de politique'), ('CONNEXION', 'Connexion'), ('CONNEXION_ECHOUEE', 'Échec de connexion'), ('CONNEXION_REFUSEE_VERROUILLEE', 'Connexion refusée : compte verrouillé'), ('MFA_ETAPSE_DEMANDEE', 'Étape MFA demandée à la connexion'), ('MFA_ACTIVE', 'Activation du MFA (TOTP)'), ('MFA_DESACTIVE', 'Désactivation du MFA (TOTP)'), ('DECONNEXION', 'Déconnexion'), ('SESSION_REVOQUEE', 'Révocation de session'), ('APPAREIL_REVOQUE', 'Révocation d’appareil'), ('ACCES_REFUSE', 'Accès refusé sur ressource sensible'), ('AUTO_ELEVATION_TENTEE', 'Tentative d’auto-élévation'), ('TRANSITION_REFUSEE', 'Transition de statut refusée'), ('PROPOSITION_DEPOSEE', 'Proposition de provisionnement déposée'), ('PROPOSITION_APPROUVEE', 'Proposition approuvée'), ('PROPOSITION_REJETEE', 'Proposition rejetée'), ('IMPORT_EXECUTE', 'Exécution d’import en masse'), ('IMPORTA_ANNULE', 'Annulation d’import en masse'), ('EXPIRATION_AUTO', 'Expiration automatique à terme'), ('DELEGATION_ACTIVEE', 'Activation de délégation'), ('ACTION_DELEGUEE', 'Action exercée par délégation'), ('ORGANISATION_MODIFIEE', 'Modification de l’organisation (direction, département, service, rattachement)'), ('ORGANISATION_CREEE', 'Création d’une unité d’organigramme'), ('ORGANISATION_DESACTIVEE', 'Désactivation d’une unité d’organigramme'), ('ROLE_VERSIONNE', 'Versionnement de rôle'), ('ROLE_RESTAURE', 'Restauration d’une version de rôle'), ('DEMANDE_ACCES_CREEE', 'Création d’une demande d’accès'), ('DEMANDE_ACCES_SOUMISE', 'Soumission d’une demande d’accès'), ('DEMANDE_ACCES_EN_REVUE', 'Demande d’accès placée en revue'), ('DEMANDE_ACCES_APPROUVEE', 'Demande d’accès approuvée'), ('DEMANDE_ACCES_REFUSEE', 'Demande d’accès refusée'), ('DEMANDE_ACCES_ANNULEE', 'Demande d’accès annulée'), ('AUTRE', 'Autre événement')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='DemandeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('ATTRIBUTION_ROLE', 'Attribution de rôle'), ('PERMISSION_DIRECTE', 'Permission directe (dérogation)')], max_length=20)),
                ('justification', models.TextField(help_text='Justification métier obligatoire de la demande.')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_REVUE', 'En revue'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=12)),
                ('motif_decision', models.TextField(blank=True, default='')),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approbateur', models.ForeignKey(blank=True, help_text='Validateur ayant décidé (jamais le demandeur lui-même).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_acces_traitees', to=settings.AUTH_USER_MODEL)),
                ('compte_cible', models.ForeignKey(blank=True, help_text='Compte bénéficiaire de l’accès demandé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_acces', to='habilitations.compteutilisateur')),
                ('demandeur', models.ForeignKey(blank=True, help_text='Administrateur ayant formulé la demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_acces_emises', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_acces', to='habilitations.permissionmetier')),
                ('proposition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_acces_origine', to='habilitations.propositionprovisionnement')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_acces', to='habilitations.rolemetier')),
            ],
            options={
                'verbose_name': 'Demande d’accès',
                'verbose_name_plural': 'Demandes d’accès',
                'ordering': ('-date_creation',),
                'indexes': [models.Index(fields=['statut', 'type_demande'], name='habilitatio_statut_c92ece_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('approbateur', models.F('demandeur')), _negated=True), name='hab_demande_pas_auto_approbation')],
            },
        ),
    ]
