# Generated by Django 5.1.4 on 2026-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurys', '0002_notificationjury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionjury',
            name='decision',
            field=models.CharField(choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('ADMIS_RESERVES', 'Admis avec réserves'), ('EXCLUSION', 'Exclu')], max_length=20),
        ),
    ]
