# Generated by Django 5.1.4 on 2026-09-13 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteurCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=64, unique=True)),
                ('dernier_numero', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compteur de codes',
                'verbose_name_plural': 'Compteurs de codes',
            },
        ),
        migrations.CreateModel(
            name='EvenementAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('source', models.CharField(choices=[('presences', 'Présences'), ('scolarite', 'Scolarité'), ('referentiels', 'Référentiels'), ('core', 'Noyau')], db_index=True, max_length=30)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('horodatage', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acteur_label', models.CharField(blank=True, max_length=150)),
                ('object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('objet_type', models.CharField(blank=True, max_length=100)),
                ('objet_id', models.CharField(blank=True, max_length=64)),
                ('objet_libelle', models.CharField(blank=True, max_length=255)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('source_entree_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_audit_core', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Événement d’audit',
                'verbose_name_plural': 'Journal d’audit unifié',
                'ordering': ['-horodatage', '-id'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['source', 'action'], name='core_evenem_source_0b1f48_idx'), models.Index(fields=['content_type', 'object_id'], name='core_audit_cible_idx'), models.Index(fields=['acteur', 'horodatage'], name='core_evenem_acteur__472816_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_entree_id__isnull', False)), fields=('source', 'source_entree_id'), name='core_audit_une_replique_par_source')],
            },
        ),
    ]
