# Generated by Django 5.1.4 on 2026-09-07 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_campagneadmission_candidature_campagne_and_more'),
        ('formations', '0088_alter_participant_options'),
        ('scolarite', '0009_alter_evenementscolarite_type_evenement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeEquivalenceDispense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('EQUIVALENCE', 'Équivalence'), ('DISPENSE', 'Dispense')], max_length=15)),
                ('etablissement_origine', models.CharField(blank=True, default='', max_length=200)),
                ('analyse_pedagogique', models.TextField(blank=True, default='')),
                ('commission', models.CharField(blank=True, default='', max_length=200)),
                ('date_commission', models.DateField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], default='EN_ATTENTE', max_length=15)),
                ('credits_reconnus', models.PositiveSmallIntegerField(blank=True, help_text='Crédits ECTS reconnus (équivalence).', null=True)),
                ('note_transferee', models.DecimalField(blank=True, decimal_places=2, help_text='Note transférée éventuelle (sur 20).', max_digits=5, null=True)),
                ('motif', models.TextField(blank=True, default='')),
                ('autorite_validation', models.CharField(blank=True, default='', max_length=200)),
                ('date_effet', models.DateField(blank=True, null=True)),
                ('fin_validite', models.DateField(blank=True, help_text='Au-delà, la dispense/équivalence n’est plus applicable.', null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_INSTRUCTION', 'En instruction'), ('A_COMPLETER', 'À compléter'), ('AVIS_PEDAGOGIQUE', 'Avis pédagogique'), ('DECISION', 'Décision'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('APPLIQUEE', 'Appliquée')], default='BROUILLON', max_length=20)),
                ('appliquee_le', models.DateTimeField(blank=True, null=True)),
                ('rectifiee_le', models.DateTimeField(blank=True, null=True)),
                ('motif_rectification', models.TextField(blank=True, default='')),
                ('decision_rectifiee', models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_equivalence', to='scolarite.anneeacademique')),
                ('appliquee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equivalences_appliquees', to=settings.AUTH_USER_MODEL)),
                ('ecue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_equivalence', to='scolarite.ecue')),
                ('etudiant', models.ForeignKey(help_text='Rattaché au dossier étudiant (matricule porté par Participant).', on_delete=django.db.models.deletion.PROTECT, related_name='demandes_equivalence', to='scolarite.dossieretudiant')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_equivalence', to='scolarite.niveau')),
                ('parcours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_equivalence', to='scolarite.parcours')),
                ('ref_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_equivalence', to='formations.refformation')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_equivalence', to='scolarite.semestre')),
                ('ue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_equivalence', to='scolarite.ue')),
            ],
            options={
                'verbose_name': 'Équivalence/Dispense – Demande',
                'verbose_name_plural': 'Équivalences/Dispenses – Demandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEquivalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('EN_INSTRUCTION', 'En instruction'), ('A_COMPLETER', 'À compléter'), ('AVIS_PEDAGOGIQUE', 'Avis pédagogique'), ('DECISION', 'Décision'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('APPLIQUEE', 'Appliquée')], max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('EN_ATTENTE', 'En attente'), ('FAVORABLE', 'Favorable'), ('DEFAVORABLE', 'Défavorable')], default='', max_length=15)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('horodatage', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('diplome_origine', models.CharField(blank=True, default='', max_length=200)),
                ('annee_obtention', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='equivalences.demandeequivalencedispense')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_equivalences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Équivalence/Dispense – Historique',
                'verbose_name_plural': 'Équivalences/Dispenses – Historiques',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='PieceEquivalence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, default='', max_length=200)),
                ('obligatoire', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('MANQUANTE', 'Manquante'), ('FOURNIE', 'Fournie'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='MANQUANTE', max_length=15)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='equivalences.demandeequivalencedispense')),
                ('type_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pieces_equivalence', to='admissions.typepiece')),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_equivalence_verifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Équivalence/Dispense – Pièce',
                'verbose_name_plural': 'Équivalences/Dispenses – Pièces',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='demandeequivalencedispense',
            index=models.Index(fields=['etudiant', 'statut'], name='equivalence_etudian_6eac68_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeequivalencedispense',
            index=models.Index(fields=['type_demande', 'statut'], name='equivalence_type_de_07b650_idx'),
        ),
    ]
