# Generated by Django 5.1.4 on 2026-09-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equivalences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeequivalencedispense',
            name='annee_obtention',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeequivalencedispense',
            name='diplome_origine',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
