# Generated by Django 5.2.16 on 2026-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_attendancesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'code']},
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('maintenance', 'En maintenance'), ('reserved', 'Réservée'), ('inactive', 'Inactive')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(blank=True, choices=[('ENSEPS', 'Bloc ENSEPS'), ('ENSEP', 'Bloc ENSEP'), ('LMD', 'Bâtiment LMD'), ('CNMS', 'Centre National de Médecine du Sport'), ('CNSHN', 'Centre National du Sport de Haut Niveau'), ('GYM', 'Gymnases'), ('EXT', 'Installations sportives extérieures'), ('LAB', 'Laboratoires pédagogiques'), ('NUM', 'Espaces numériques'), ('RECH', 'Espaces de recherche'), ('BIB', 'Bibliothèque'), ('SPEC', 'Salles spécialisées'), ('ADM', 'Espaces administratifs'), ('POLY', 'Espaces polyvalents'), ('RES', 'Résidences pédagogiques'), ('CAMPUS', 'Espaces extérieurs campus')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('amphitheater', 'Amphithéâtre'), ('classroom', 'Salle de cours'), ('td', 'Salle de TD'), ('tp', 'Salle de TP'), ('lab', 'Laboratoire'), ('computer', 'Salle informatique'), ('gym', 'Gymnase'), ('medical', 'Médecine du sport'), ('sport', 'Installation sportive'), ('conference', 'Salle de conférence'), ('seminar', 'Salle de séminaire'), ('library', 'Bibliothèque'), ('research', 'Espace recherche'), ('admin', 'Espace administratif'), ('residence', 'Résidence'), ('outdoor', 'Espace extérieur'), ('specialized', 'Salle spécialisée')], db_index=True, default='classroom', max_length=20),
        ),
    ]
