# Generated by Django 5.2.16 on 2026-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_campus_ops_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], db_index=True, max_length=1),
        ),
    ]
