# Generated by Django 5.2 on 2026-08-18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_teacher_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='supervisor',
            field=models.ForeignKey(
                blank=True,
                help_text='Encadrant pédagogique (TP, stages, séances pratiques).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='supervised_assignments',
                to='faculty.teacher',
                verbose_name='Encadrant',
            ),
        ),
        migrations.AddField(
            model_name='schedule',
            name='session_kind',
            field=models.CharField(
                choices=[('cm', 'Cours magistral'), ('td', 'Travaux dirigés'), ('tp', 'Travaux pratiques')],
                db_index=True,
                default='cm',
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name='schedule',
            name='supervisor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='supervised_schedules',
                to='faculty.teacher',
                verbose_name='Encadrant de séance',
            ),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='supervisor_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='supervisor_checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='supervisor_checked_in_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='checked_in_supervised_sessions',
                to='faculty.teacher',
            ),
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('role', models.CharField(
                    choices=[('formateur', 'Formateur'), ('encadrant', 'Encadrant')],
                    db_index=True,
                    max_length=15,
                )),
                ('status', models.CharField(
                    choices=[
                        ('present', 'Présent'),
                        ('absent', 'Absent'),
                        ('late', 'Retard'),
                        ('excused', 'Excusé'),
                    ],
                    default='present',
                    max_length=10,
                )),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('recorded_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='recorded_staff_attendances',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('schedule', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='staff_attendances',
                    to='faculty.schedule',
                )),
                ('teacher', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='staff_attendances',
                    to='faculty.teacher',
                )),
            ],
            options={
                'verbose_name': 'Présence personnel pédagogique',
                'verbose_name_plural': 'Présences personnel pédagogique',
                'ordering': ['-date', 'role'],
                'unique_together': {('teacher', 'schedule', 'date', 'role')},
            },
        ),
    ]
