# Generated by Django 5.2.16 on 2026-08-21 09:56

import apps.faculty.models
import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_formationperiod_holiday'),
        ('faculty', '0007_badge_security'),
        ('students', '0002_maquette_staps2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('max_students', models.PositiveSmallIntegerField(default=25)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='academics.promotion')),
            ],
            options={
                'verbose_name': 'Groupe pédagogique',
                'verbose_name_plural': 'Groupes pédagogiques',
                'ordering': ['promotion', 'name'],
                'unique_together': {('promotion', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GroupSchedulingConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('morning_enabled', models.BooleanField(default=True)),
                ('morning_start', models.TimeField(default=datetime.time(8, 0))),
                ('morning_end', models.TimeField(default=datetime.time(12, 0))),
                ('afternoon_enabled', models.BooleanField(default=True)),
                ('afternoon_start', models.TimeField(default=datetime.time(14, 0))),
                ('afternoon_end', models.TimeField(default=datetime.time(18, 0))),
                ('active_days', models.JSONField(blank=True, default=apps.faculty.models.default_active_days)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_config', to='faculty.studentgroup')),
            ],
            options={
                'verbose_name': 'Disponibilités du groupe',
                'verbose_name_plural': 'Disponibilités des groupes',
            },
        ),
        migrations.CreateModel(
            name='PlanningSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_global', models.BooleanField(db_index=True, default=False, editable=False)),
                ('morning_start', models.TimeField(default=datetime.time(8, 0))),
                ('morning_end', models.TimeField(default=datetime.time(12, 0))),
                ('afternoon_start', models.TimeField(default=datetime.time(14, 0))),
                ('afternoon_end', models.TimeField(default=datetime.time(18, 0))),
                ('active_days', models.JSONField(blank=True, default=apps.faculty.models.default_active_days, help_text='Jours ouvrés, 0 = lundi.')),
                ('session_duration_minutes', models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(30)])),
                ('max_sessions_per_day', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_rooms_per_course', models.PositiveSmallIntegerField(default=10, help_text='Salles mobilisables simultanément pour un même ECUE.', validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_tolerance', models.PositiveSmallIntegerField(default=0, help_text='Étudiants tolérés au-delà de la capacité d’une salle.')),
                ('lock_room_per_group', models.BooleanField(default=False, help_text='Conserver la même salle pour un groupe sur toute la période.')),
                ('spread_remainder', models.BooleanField(default=False, help_text='Étaler le reliquat horaire sur les séances déjà placées.')),
                ('weight_capacity_gap', models.PositiveSmallIntegerField(default=10)),
                ('weight_room_rotation', models.PositiveSmallIntegerField(default=2)),
                ('weight_global_balance', models.PositiveSmallIntegerField(default=1)),
                ('period', models.OneToOneField(blank=True, help_text='Vide = réglages par défaut de l’établissement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_settings', to='academics.formationperiod')),
            ],
            options={
                'verbose_name': 'Paramètres de planification',
                'verbose_name_plural': 'Paramètres de planification',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_global', True)), fields=('is_global',), name='uniq_global_planning_settings')],
            },
        ),
        migrations.CreateModel(
            name='StudentGroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='faculty.studentgroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='students.student')),
            ],
            options={
                'verbose_name': 'Membre de groupe pédagogique',
                'verbose_name_plural': 'Membres de groupes pédagogiques',
                'unique_together': {('group', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_kind', models.CharField(choices=[('cm', 'Cours magistral'), ('td', 'Travaux dirigés'), ('tp', 'Travaux pratiques')], db_index=True, default='cm', max_length=5)),
                ('hours_total', models.PositiveSmallIntegerField(help_text='Volume horaire à répartir sur la période.', validators=[django.core.validators.MinValueValidator(1)])),
                ('slot_mode', models.CharField(choices=[('morning', 'Matin uniquement'), ('afternoon', 'Après-midi uniquement'), ('both', 'Matin et après-midi')], default='both', max_length=10)),
                ('preferred_room_type', models.CharField(blank=True, choices=[('amphitheater', 'Amphithéâtre'), ('classroom', 'Salle de cours'), ('td', 'Salle de TD'), ('tp', 'Salle de TP'), ('lab', 'Laboratoire'), ('computer', 'Salle informatique'), ('gym', 'Gymnase'), ('medical', 'Médecine du sport'), ('sport', 'Installation sportive'), ('conference', 'Salle de conférence'), ('seminar', 'Salle de séminaire'), ('library', 'Bibliothèque'), ('research', 'Espace recherche'), ('admin', 'Espace administratif'), ('residence', 'Résidence'), ('outdoor', 'Espace extérieur'), ('specialized', 'Salle spécialisée')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_loads', to='academics.course')),
                ('group', models.ForeignKey(blank=True, help_text='Vide = promotion entière.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='faculty.studentgroup')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='academics.formationperiod')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_loads', to='academics.promotion')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_teaching_loads', to='faculty.teacher', verbose_name='Encadrant')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_loads', to='faculty.teacher')),
            ],
            options={
                'verbose_name': 'Charge à planifier',
                'verbose_name_plural': 'Charges à planifier',
                'ordering': ['period', 'course'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('period', 'course', 'promotion', 'group', 'session_kind'), name='uniq_teaching_load_per_group'), models.UniqueConstraint(condition=models.Q(('group__isnull', True)), fields=('period', 'course', 'promotion', 'session_kind'), name='uniq_teaching_load_per_promotion')],
            },
        ),
    ]
