# Generated by Django 5.2.16 on 2026-08-21 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_formationperiod_holiday'),
        ('faculty', '0008_studentgroup_groupschedulingconfig_planningsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_kind', models.CharField(choices=[('cm', 'Cours magistral'), ('td', 'Travaux dirigés'), ('tp', 'Travaux pratiques')], db_index=True, default='cm', max_length=5)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('generated', 'Généré'), ('validated', 'Validé'), ('published', 'Publié'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('cancelled', 'Annulé'), ('archived', 'Archivé')], db_index=True, default='draft', max_length=15)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('teacher_checked_in', models.BooleanField(default=False)),
                ('teacher_checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_checked_in', models.BooleanField(default=False)),
                ('supervisor_checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='academics.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_seances', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Vide = promotion entière.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='faculty.studentgroup')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='academics.formationperiod')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='academics.promotion')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='faculty.room')),
                ('schedule', models.ForeignKey(blank=True, help_text='Gabarit hebdomadaire dont la séance est issue, le cas échéant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='faculty.schedule')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_seances', to='faculty.teacher', verbose_name='Encadrant')),
                ('supervisor_checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_supervised_seances', to='faculty.teacher')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='faculty.teacher')),
                ('teacher_checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_seances', to='faculty.teacher')),
                ('teaching_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='faculty.teachingload')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='seance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='faculty.seance'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='seance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendances', to='faculty.seance'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['date', 'status'], name='faculty_sea_date_27ae57_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['promotion', 'date'], name='faculty_sea_promoti_8bb2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['teacher', 'date'], name='faculty_sea_teacher_6584c5_idx'),
        ),
        migrations.AddIndex(
            model_name='seance',
            index=models.Index(fields=['room', 'date'], name='faculty_sea_room_id_21b3e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='seance',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'date'), name='uniq_seance_per_schedule_and_date'),
        ),
    ]
