# Generated by Django 5.2.16 on 2026-08-21 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_formationperiod_holiday'),
        ('faculty', '0010_backfill_seances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('best_effort', 'Meilleur effort'), ('strict', 'Strict')], default='best_effort', max_length=20)),
                ('status', models.CharField(choices=[('running', 'En cours'), ('done', 'Terminé'), ('error', 'Erreur')], db_index=True, default='running', max_length=10)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_runs', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_runs', to='academics.formationperiod')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_runs', to='academics.promotion')),
            ],
            options={
                'verbose_name': 'Exécution de planification',
                'verbose_name_plural': 'Exécutions de planification',
                'ordering': ['-started_at'],
            },
        ),
    ]
