# Generated by Django 5.2.16 on 2026-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_timetablerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planningsettings',
            name='auto_absent_after_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='Minutes après la fin prévue avant auto-absence.'),
        ),
        migrations.AddField(
            model_name='planningsettings',
            name='late_after_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Minutes après le début prévu pour qualifier un retard.'),
        ),
        migrations.AddField(
            model_name='planningsettings',
            name='partial_under_percent',
            field=models.PositiveSmallIntegerField(default=75, help_text='Présence partielle sous ce pourcentage de la durée prévue.'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='late_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'Retard'), ('partial', 'Présence partielle'), ('excused', 'Excusé')], default='present', max_length=10),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('late', 'Retard'), ('partial', 'Présence partielle'), ('excused', 'Excusé')], default='present', max_length=10),
        ),
    ]
