# Generated by Django 5.2.16 on 2026-08-21 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_attendance_clock_and_rules'),
        ('students', '0002_maquette_staps2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('check_in', 'Entrée'), ('check_out', 'Sortie'), ('correction', 'Correction'), ('force', 'Forçage'), ('auto_absent', 'Auto-absence')], db_index=True, max_length=20)),
                ('source', models.CharField(choices=[('qr', 'QR'), ('admin', 'Administration'), ('teacher', 'Formateur'), ('system', 'Système')], db_index=True, default='qr', max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session_date', models.DateField(db_index=True)),
                ('previous_status', models.CharField(blank=True, max_length=10)),
                ('new_status', models.CharField(blank=True, max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_events', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_events', to='faculty.attendance')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_events', to='faculty.schedule')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badge_events', to='faculty.seance')),
                ('staff_attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_events', to='faculty.staffattendance')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_events', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge_events', to='faculty.teacher')),
            ],
            options={
                'verbose_name': 'Événement de badgeage',
                'verbose_name_plural': 'Événements de badgeage',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['student', '-occurred_at'], name='faculty_bad_student_4c4314_idx'), models.Index(fields=['seance', 'kind'], name='faculty_bad_seance__4d92a7_idx'), models.Index(fields=['attendance', '-occurred_at'], name='faculty_bad_attenda_bc4eb3_idx')],
            },
        ),
    ]
