# Generated by Django 5.1.4 on 2026-09-01 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(db_index=True, help_text='Identifiant technique unique (ex: finance_prix_heure_realisee)', max_length=100, unique=True)),
                ('libelle', models.CharField(help_text="Libellé affiché à l'utilisateur", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description complète ou aide contextuelle')),
                ('categorie', models.CharField(choices=[('general', 'Général'), ('finance', 'Finance'), ('presences', 'Présences'), ('securite', 'Sécurité'), ('interface', 'Interface')], db_index=True, max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=100, help_text="Ordre d'affichage au sein de la catégorie (croissant)")),
                ('type', models.CharField(choices=[('text', 'Texte libre'), ('email', 'Email'), ('integer', 'Nombre entier'), ('decimal', 'Décimal'), ('bool', 'Booléen'), ('choice', 'Liste déroulante'), ('date', 'Date')], default='text', max_length=20)),
                ('valeur', models.TextField(help_text='Valeur courante (stockée en JSON si nécessaire)')),
                ('valeur_defaut', models.TextField(help_text='Valeur par défaut (pour restauration)')),
                ('choices_json', models.TextField(blank=True, default='', help_text='Pour type=choice: {"key": "Libellé", ...} en JSON')),
                ('regex_validation', models.CharField(blank=True, default='', help_text='Regex pour validation custom (optionnel)', max_length=500)),
                ('modifiable', models.BooleanField(default=True, help_text='Si False, le paramètre ne peut pas être modifié')),
                ('modifiable_par_roles', models.TextField(default='["ADMIN", "CHEF_CPFAE_ADMIN", "CPFAE_ADMIN"]', help_text='Rôles autorisés à modifier (JSON array)')),
                ('lecturable_par_roles', models.TextField(default='["ADMIN", "CHEF_CPFAE_ADMIN", "CPFAE_ADMIN", "DIRECTION", "FINANCE"]', help_text='Rôles autorisés à consulter (JSON array)')),
                ('actif', models.BooleanField(db_index=True, default=True, help_text='Paramètre actif/inactif')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_crees', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['categorie', 'ordre', 'libelle'],
                'permissions': [('view_parametres', 'Consulter les paramètres'), ('change_parametres', 'Modifier les paramètres')],
            },
        ),
        migrations.CreateModel(
            name='ParametreHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.TextField(help_text='Valeur précédente du paramètre')),
                ('nouvelle_valeur', models.TextField(help_text='Nouvelle valeur du paramètre')),
                ('modifie_le', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('motif_modification', models.TextField(blank=True, default='', help_text='Raison optionnelle de la modification')),
                ('adresse_ip', models.CharField(blank=True, default='', help_text='Adresse IP du client ayant effectué la modification', max_length=50)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_parametres', to=settings.AUTH_USER_MODEL)),
                ('parametre', models.ForeignKey(help_text='Paramètre concerné par cette modification', on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='parametres.parametre')),
            ],
            options={
                'verbose_name': 'Historique paramètre',
                'verbose_name_plural': 'Historique paramètres',
                'ordering': ['-modifie_le'],
            },
        ),
        migrations.AddIndex(
            model_name='parametre',
            index=models.Index(fields=['categorie', 'actif'], name='param__categ_actif_idx'),
        ),
        migrations.AddIndex(
            model_name='parametre',
            index=models.Index(fields=['cle'], name='param__cle_idx'),
        ),
        migrations.AddIndex(
            model_name='parametre',
            index=models.Index(fields=['modifie_le'], name='param__modif_date_idx'),
        ),
        migrations.AddIndex(
            model_name='parametrehistorique',
            index=models.Index(fields=['parametre', 'modifie_le'], name='hist__param_date_idx'),
        ),
        migrations.AddIndex(
            model_name='parametrehistorique',
            index=models.Index(fields=['modifie_le'], name='hist__modif_date_idx'),
        ),
    ]
