# Generated by Django 5.1.4 on 2026-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0008_flags_lot2_securite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre',
            name='lecturable_par_roles',
            field=models.TextField(default='["ADMIN", "CHEF_INJS_ADMIN", "INJS_ADMIN", "DIRECTION", "FINANCE"]', help_text='Rôles autorisés à consulter (JSON array)'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='modifiable_par_roles',
            field=models.TextField(default='["ADMIN", "CHEF_INJS_ADMIN", "INJS_ADMIN"]', help_text='Rôles autorisés à modifier (JSON array)'),
        ),
    ]
