name: TEST RUNNER

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, macOS, ARM64, backend-injs]
    steps:
      - name: Test GitHub-hosted runner
        run: |
          echo "RUNNER OK"
          uname -a
          node --version
          python3 --version
